/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGestionVenta;

import controladorGestionCliente.ControladorCliente;
import controladorGestionInventario.ControladorInventario;
import controladorGestionUsuario.ControladorMenu;
import controladorGestionVenta.ControladorVenta;
import java.util.ArrayList;
import modeloGestionUsuario.Usuario;
import javax.swing.*;
import javax.swing.table.TableCellRenderer;
import modeloGestionCliente.Cliente;
import modeloGestionInventario.Producto;
import modeloGestionVenta.Factura;
import modeloGestionVenta.ItemFactura;


/**
 *
 * @author Aidis
 */
public class VentanaGenerarFactura extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public VentanaGenerarFactura(Usuario user) {
        initComponents();
        //Centra la ventana
        this.setLocationRelativeTo(null);
        this.user = user;
        controlInv = new ControladorInventario();
        controlMenu = new ControladorMenu();
        controlVenta = new ControladorVenta();
        controlClient = new ControladorCliente();
        jLabelUserName.setText(user.getNombreUsuario());
        centrarNCamposJTable(jTProductos);
        nroItem =0;
        factura =new Factura();
        items = new ArrayList<>();
    }
    
    private void centrarNCamposJTable(JTable tabla)
    {
        TableCellRenderer rendererFromHeader = tabla.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jLCodigo = new javax.swing.JLabel();
        jAstCodigo = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jTFUsuario = new javax.swing.JTextField();
        jLUsuario = new javax.swing.JLabel();
        jAstUsuario = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jBRemoveProduct = new javax.swing.JLabel();
        jSeparatorUsuario1 = new javax.swing.JSeparator();
        jTFTotal = new javax.swing.JLabel();
        jTFFecha = new javax.swing.JTextField();
        jLFecha = new javax.swing.JLabel();
        jAstFecha = new javax.swing.JLabel();
        jLCliente = new javax.swing.JLabel();
        jTFProducto = new javax.swing.JTextField();
        jBCliente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProductos = new javax.swing.JTable();
        jTFCliente = new javax.swing.JTextField();
        jLProducto = new javax.swing.JLabel();
        jSeparatorUsuario2 = new javax.swing.JSeparator();
        jTFNombre = new javax.swing.JLabel();
        jLTotal = new javax.swing.JButton();
        jBbuscar = new javax.swing.JLabel();
        jBAddProduct = new javax.swing.JLabel();
        jTFCantidad = new javax.swing.JTextField();
        jLUsuario1 = new javax.swing.JLabel();
        jAstCantidad = new javax.swing.JLabel();
        jPanelLateralI = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelWindowTitle = new javax.swing.JLabel();
        jLabelMiniUser1 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jPanelLateralD = new javax.swing.JPanel();
        jBInformacion = new javax.swing.JLabel();
        jBUno = new javax.swing.JLabel();
        jBDos = new javax.swing.JLabel();
        jBTres = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();
        jBSalir = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCodigo.setBackground(new java.awt.Color(0, 0, 0));
        jLCodigo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCodigo.setText("CODIGO");
        jPanelMenu.add(jLCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jAstCodigo.setBackground(new java.awt.Color(0, 0, 0));
        jAstCodigo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstCodigo.setForeground(new java.awt.Color(255, 102, 51));
        jAstCodigo.setText("*");
        jPanelMenu.add(jAstCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jTFCodigo.setBackground(new java.awt.Color(220, 220, 220));
        jTFCodigo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCodigo.setForeground(new java.awt.Color(102, 102, 102));
        jTFCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelMenu.add(jTFCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 150, 30));

        jTFUsuario.setBackground(new java.awt.Color(220, 220, 220));
        jTFUsuario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jTFUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelMenu.add(jTFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 110, 30));

        jLUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jLUsuario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLUsuario.setText("CANTIDAD");
        jPanelMenu.add(jLUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        jAstUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jAstUsuario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstUsuario.setForeground(new java.awt.Color(255, 102, 51));
        jAstUsuario.setText("*");
        jPanelMenu.add(jAstUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        jLNombre.setBackground(new java.awt.Color(0, 0, 0));
        jLNombre.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNombre.setText("NOMBRE ");
        jPanelMenu.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        jBRemoveProduct.setBackground(new java.awt.Color(0, 0, 0));
        jBRemoveProduct.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBRemoveProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBRemoveProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconRemoveProduct.png"))); // NOI18N
        jBRemoveProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBRemoveProductMouseClicked(evt);
            }
        });
        jPanelMenu.add(jBRemoveProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, -1, 30));

        jSeparatorUsuario1.setForeground(new java.awt.Color(255, 102, 51));
        jPanelMenu.add(jSeparatorUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 100, 10));

        jTFTotal.setBackground(new java.awt.Color(255, 255, 255));
        jTFTotal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFTotal.setForeground(new java.awt.Color(102, 102, 102));
        jTFTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFTotal.setOpaque(true);
        jPanelMenu.add(jTFTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 100, 30));

        jTFFecha.setBackground(new java.awt.Color(220, 220, 220));
        jTFFecha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFFecha.setForeground(new java.awt.Color(102, 102, 102));
        jTFFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelMenu.add(jTFFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 180, 30));

        jLFecha.setBackground(new java.awt.Color(0, 0, 0));
        jLFecha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFecha.setText("FECHA");
        jPanelMenu.add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jAstFecha.setBackground(new java.awt.Color(0, 0, 0));
        jAstFecha.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstFecha.setForeground(new java.awt.Color(255, 102, 51));
        jAstFecha.setText("*");
        jPanelMenu.add(jAstFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLCliente.setBackground(new java.awt.Color(0, 0, 0));
        jLCliente.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCliente.setText(" CLIENTE");
        jPanelMenu.add(jLCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        jTFProducto.setBackground(new java.awt.Color(220, 220, 220));
        jTFProducto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFProducto.setForeground(new java.awt.Color(102, 102, 102));
        jTFProducto.setText("Buscar");
        jTFProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jTFProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFProductoMouseClicked(evt);
            }
        });
        jPanelMenu.add(jTFProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 400, 30));

        jBCliente.setBackground(new java.awt.Color(0, 0, 0));
        jBCliente.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconsAddUser.png"))); // NOI18N
        jBCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBClienteMouseClicked(evt);
            }
        });
        jPanelMenu.add(jBCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, 30));

        jScrollPane2.setBackground(new java.awt.Color(220, 220, 220));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jTProductos.setBackground(new java.awt.Color(220, 220, 220));
        jTProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "DESCRIPCIÓN", "PRECIO", "CANTIDAD"
            }
        ));
        jTProductos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTProductos.setFillsViewportHeight(true);
        jTProductos.setGridColor(new java.awt.Color(255, 102, 51));
        jTProductos.setName(""); // NOI18N
        jTProductos.setRowHeight(30);
        jTProductos.setSurrendersFocusOnKeystroke(true);
        jTProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTProductos);

        jPanelMenu.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 770, 170));

        jTFCliente.setBackground(new java.awt.Color(220, 220, 220));
        jTFCliente.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCliente.setForeground(new java.awt.Color(102, 102, 102));
        jTFCliente.setText("Buscar");
        jTFCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jTFCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFClienteMouseClicked(evt);
            }
        });
        jPanelMenu.add(jTFCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 220, 30));

        jLProducto.setBackground(new java.awt.Color(0, 0, 0));
        jLProducto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLProducto.setText("PRODUCTO");
        jPanelMenu.add(jLProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 30));

        jSeparatorUsuario2.setForeground(new java.awt.Color(255, 102, 51));
        jPanelMenu.add(jSeparatorUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 280, 10));

        jTFNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTFNombre.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFNombre.setForeground(new java.awt.Color(102, 102, 102));
        jTFNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFNombre.setOpaque(true);
        jPanelMenu.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 280, 30));

        jLTotal.setBackground(new java.awt.Color(255, 255, 255));
        jLTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLTotal.setText("TOTAL");
        jLTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jLTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMenu.add(jLTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 60, 30));

        jBbuscar.setBackground(new java.awt.Color(0, 0, 0));
        jBbuscar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBbuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconSearch.png"))); // NOI18N
        jBbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBbuscarMouseClicked(evt);
            }
        });
        jPanelMenu.add(jBbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, 30));

        jBAddProduct.setBackground(new java.awt.Color(0, 0, 0));
        jBAddProduct.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBAddProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconAddProduct.png"))); // NOI18N
        jBAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAddProductMouseClicked(evt);
            }
        });
        jPanelMenu.add(jBAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, -1, 30));

        jTFCantidad.setBackground(new java.awt.Color(220, 220, 220));
        jTFCantidad.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCantidad.setForeground(new java.awt.Color(102, 102, 102));
        jTFCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelMenu.add(jTFCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 50, 30));

        jLUsuario1.setBackground(new java.awt.Color(0, 0, 0));
        jLUsuario1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLUsuario1.setText("CAJERO");
        jPanelMenu.add(jLUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        jAstCantidad.setBackground(new java.awt.Color(0, 0, 0));
        jAstCantidad.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstCantidad.setForeground(new java.awt.Color(255, 102, 51));
        jAstCantidad.setText("*");
        jPanelMenu.add(jAstCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 20, -1));

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 850, 420));

        jPanelLateralI.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLateralI.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLateralI.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanelLateralI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelLateralI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 100, 510));

        jPanelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelWindowTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelWindowTitle.setForeground(new java.awt.Color(255, 102, 51));
        jLabelWindowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWindowTitle.setText("FORMULARIO REGISTRO FACTURA");
        jPanelTitulo.add(jLabelWindowTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 530, -1));

        jLabelMiniUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconUserMini.png"))); // NOI18N
        jPanelTitulo.add(jLabelMiniUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        jLabelUserName.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUserName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Administrador");
        jPanelTitulo.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 90, -1));

        getContentPane().add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 100));

        jPanelLateralD.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLateralD.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLateralD.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanelLateralD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconInformation.png"))); // NOI18N
        jBInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBInformacionMouseClicked(evt);
            }
        });
        jPanelLateralD.add(jBInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jBUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon1.png"))); // NOI18N
        jBUno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBUnoMouseClicked(evt);
            }
        });
        jPanelLateralD.add(jBUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jBDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon2.png"))); // NOI18N
        jBDos.setToolTipText("");
        jBDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBDosMouseClicked(evt);
            }
        });
        jPanelLateralD.add(jBDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jBTres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon3.png"))); // NOI18N
        jBTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTresMouseClicked(evt);
            }
        });
        jPanelLateralD.add(jBTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        getContentPane().add(jPanelLateralD, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 100, 510));

        jPanelBotones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBSalir.setBackground(new java.awt.Color(204, 204, 255));
        jBSalir.setText("SALIR");
        jBSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jBSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSalirMouseClicked(evt);
            }
        });
        jPanelBotones.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 120, 40));

        jBGuardar.setBackground(new java.awt.Color(204, 204, 255));
        jBGuardar.setText("GUARDAR");
        jBGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jBGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBGuardarMouseClicked(evt);
            }
        });
        jPanelBotones.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, 40));

        getContentPane().add(jPanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 850, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalirMouseClicked
        controlMenu.irModuloGVenta(user);
        this.setVisible(false);
    }//GEN-LAST:event_jBSalirMouseClicked
    
    private void borrarInfoCampos()
    {
        jTFCodigo.setText("");
        jTFFecha.setText("");
        jTFUsuario.setText("");
        jTFCantidad.setText("");
        jTFCliente.setText("");
        jTFNombre.setText("");
        jTFProducto.setText("");
        mostrarTabla(obtenerTablaVacia());
        jTFTotal.setText("");
    }
    
    private void tomarInfoFactura()
    {     
        factura.setCodigo(jTFCodigo.getText());
        factura.setFecha(jTFFecha.getText());
        factura.setCodCajero(jTFUsuario.getText());
        factura.setIdCliente(jTFCliente.getText());
    }
    
    private void registrarItemsFactura()
    {
        for(int i=0; i< items.size(); i++)
        {
            controlVenta.procesarRegistroItemFactura(items.get(i));        
        }
    }
    
    private void modificarStockProducto()
    {
        String codigo;
        int totalCantidad, nuevaCant,antiguaCant ;
       for(int i=0; i< items.size(); i++)
       {
            product = new Producto();
            codigo =items.get(i).getCodProducto();
            product =controlInv.procesarVistaProducto(codigo);
           
            antiguaCant = Integer.parseInt(product.getCantidad());
            nuevaCant = (int) items.get(i).getCantidad();
            totalCantidad= antiguaCant - nuevaCant; 
            controlInv. procesarCambioCantidadProducto("cantidad",Integer.toString(totalCantidad),codigo);
       }
    }
    
    private void agregarItemFactura()
    {
        ItemFactura itemFactura = new ItemFactura();
        nroItem ++;
        itemFactura.setNroItem(Integer.toString(nroItem));
        itemFactura.setCodFactura(jTFCodigo.getText());
        itemFactura.setCodProducto(jTFProducto.getText());
        itemFactura.setCantidad(Integer.parseInt(jTFCantidad.getText()));
        items.add(itemFactura);
        
        jTFProducto.setText("Buscar");
        jTFCantidad.setText("");
    }
    
    private void quitarItemFactura()
    {
    
        items.remove(nroItem-1);
        jTFProducto.setText("Buscar");
        jTFCantidad.setText("");
        nroItem --;
    
    }
        
    private void jBGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGuardarMouseClicked
        tomarInfoFactura();
        controlVenta.procesarRegistroFactura(factura);
        modificarStockProducto();
        registrarItemsFactura();
        borrarInfoCampos();
        items.clear();
    }//GEN-LAST:event_jBGuardarMouseClicked
    
    private void mostrarTabla(String [][] infoTabla)
    {
           jTProductos.setModel(new javax.swing.table.DefaultTableModel(
           infoTabla,
            new String [] {
                "CODIGO", "DESCRIPCIÓN", "PRECIO", "CANTIDAD"
            }
        ));
    
    }
    
    private String [][] obtenerTablaVacia()
    {
         return    new String [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            };
    }
    
    private void jTFClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFClienteMouseClicked
        jTFCliente.setText("");
    }//GEN-LAST:event_jTFClienteMouseClicked

    private void jTFProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFProductoMouseClicked
        jTFProducto.setText("");
    }//GEN-LAST:event_jTFProductoMouseClicked

    private void jBAddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAddProductMouseClicked
        product.setCantidad(jTFCantidad.getText());  
        
        factura.agregarProducto(product);
        
        factura.sumarTotalPVenta(); 
        
        agregarItemFactura();
        
        obtenerTablaProductos(factura.getProductos());
        
        jTFTotal.setText(Double.toString(factura.getTotal()));
    }//GEN-LAST:event_jBAddProductMouseClicked

    private void jBbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBbuscarMouseClicked
       product = controlInv.procesarVistaProducto(jTFProducto.getText());
       
       if(controlInv.getDatoEncontrado())
       { 
            jTFCantidad.setText(product.getCantidad());
            System.out.println(product.getCantidad());
            
       }else
       {
           jTFProducto.setText("Buscar");

       }
    }//GEN-LAST:event_jBbuscarMouseClicked

    private void jBRemoveProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRemoveProductMouseClicked
        factura.quitarProducto(nroItem);
        factura.sumarTotalPVenta(); 
        quitarItemFactura();
        obtenerTablaProductos(factura.getProductos());
        jTFTotal.setText(Double.toString(factura.getTotal()));
    }//GEN-LAST:event_jBRemoveProductMouseClicked

    private void jBClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBClienteMouseClicked
        client = controlClient.procesarVistaCliente(jTFCliente.getText());
       
       if(controlClient.getEncontrado())
       { 
           jTFNombre.setText(client.getNombre());
           
       }else
       {
  
           
       }
    }//GEN-LAST:event_jBClienteMouseClicked

    private void jBInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBInformacionMouseClicked
        jTFCodigo.setText("F-002");
        jTFFecha.setText("2020-05-01");
        jTFUsuario.setText("C-002");
        jTFCliente.setText("25.616.280");
    }//GEN-LAST:event_jBInformacionMouseClicked

    private void jBUnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBUnoMouseClicked
        jTFProducto.setText("CNF-001");
    }//GEN-LAST:event_jBUnoMouseClicked

    private void jBDosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDosMouseClicked
        jTFProducto.setText("BBD-001");
    }//GEN-LAST:event_jBDosMouseClicked

    private void jBTresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTresMouseClicked
        jTFProducto.setText("USO-001");
    }//GEN-LAST:event_jBTresMouseClicked
    
    private String [][] obtenerTablaProductosSub(ArrayList<Producto> products, 
                                                                String [][] imp)
    {
        for(int i=0; i< imp.length; i++)
        {
            if(i< products.size())
            {
                imp[i][0]= products.get(i).getCodigo();
                imp[i][1]= products.get(i).getDescripcion();
                imp[i][2]= products.get(i).getPrecioVenta();
                imp[i][3]= products.get(i).getCantidad();
            }else
            {
                imp[i][0]= null;
                imp[i][1]= null;
                imp[i][2]= null;
                imp[i][3]= null;           
             }
        }
        
        return imp;
    }
    
    private void obtenerTablaProductos(ArrayList<Producto> products)
    {
        String imprime[][] = new String [9][4];
        if (products.size()>0)
        {

            imprime = obtenerTablaProductosSub(products, imprime);
        }else
        {
        
            imprime = obtenerTablaVacia();
        
        }
       
         mostrarTabla( imprime);
    }

    
    private final Usuario user;
    private final  Factura factura;
    private Producto product;
    private Cliente client;
    private final ControladorInventario controlInv;
    private final ControladorVenta controlVenta;
    private final ControladorMenu controlMenu;
    private final ControladorCliente controlClient;
    private final ArrayList <ItemFactura> items;
    private int nroItem;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAstCantidad;
    private javax.swing.JLabel jAstCodigo;
    private javax.swing.JLabel jAstFecha;
    private javax.swing.JLabel jAstUsuario;
    private javax.swing.JLabel jBAddProduct;
    private javax.swing.JLabel jBCliente;
    private javax.swing.JLabel jBDos;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JLabel jBInformacion;
    private javax.swing.JLabel jBRemoveProduct;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jBTres;
    private javax.swing.JLabel jBUno;
    private javax.swing.JLabel jBbuscar;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLProducto;
    private javax.swing.JButton jLTotal;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLUsuario1;
    private javax.swing.JLabel jLabelMiniUser1;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelWindowTitle;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelLateralD;
    private javax.swing.JPanel jPanelLateralI;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparatorUsuario1;
    private javax.swing.JSeparator jSeparatorUsuario2;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTextField jTFCliente;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JLabel jTFNombre;
    private javax.swing.JTextField jTFProducto;
    private javax.swing.JLabel jTFTotal;
    private javax.swing.JTextField jTFUsuario;
    private javax.swing.JTable jTProductos;
    // End of variables declaration//GEN-END:variables
}
