/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGestionInventario;

import controladorGestionInventario.ControladorInventario;
import controladorGestionUsuario.ControladorMenu;
import modeloGestionInventario.Producto;
import modeloGestionUsuario.Usuario;

/**
 *
 * @author Aidis
 */
public class VentanaVerProducto extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public VentanaVerProducto(Usuario user) {
        initComponents();
        //Centra la ventana
        this.setLocationRelativeTo(null);
        this.user = user;
        controlInv= new ControladorInventario();
        controlMenu = new ControladorMenu();
        jLabelUserName.setText(user.getNombreUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLateralI = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelWindowTitle = new javax.swing.JLabel();
        jLabelMiniUser1 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jPanelLateralD = new javax.swing.JPanel();
        jPanelBotones = new javax.swing.JPanel();
        jBSalir = new javax.swing.JButton();
        jPanelBusqueda = new javax.swing.JPanel();
        jTFBuscar = new javax.swing.JTextField();
        jLCodigo = new javax.swing.JLabel();
        jBBuscar = new javax.swing.JLabel();
        jPanelFormulario = new javax.swing.JPanel();
        jLFecha = new javax.swing.JLabel();
        jLDescripcion = new javax.swing.JLabel();
        jLPVenta = new javax.swing.JLabel();
        jLCantidad = new javax.swing.JLabel();
        jImageProducto = new javax.swing.JLabel();
        jTFCantidad = new javax.swing.JLabel();
        jSCantidad = new javax.swing.JSeparator();
        jTFProveedor = new javax.swing.JLabel();
        jSDescripcion = new javax.swing.JSeparator();
        jTFFecha = new javax.swing.JLabel();
        jSFecha = new javax.swing.JSeparator();
        jTFPVenta = new javax.swing.JLabel();
        jSPVenta = new javax.swing.JSeparator();
        jLProveedor = new javax.swing.JLabel();
        jSProveedor = new javax.swing.JSeparator();
        jTextFieldTipo = new javax.swing.JLabel();
        jSTipo = new javax.swing.JSeparator();
        jLTipo = new javax.swing.JLabel();
        jLPCompra = new javax.swing.JLabel();
        jTFPCompra = new javax.swing.JLabel();
        jSPcompra = new javax.swing.JSeparator();
        jTFDescrip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLateralI.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLateralI.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLateralI.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanelLateralI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelLateralI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 100, 430));

        jPanelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelWindowTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelWindowTitle.setForeground(new java.awt.Color(255, 102, 51));
        jLabelWindowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWindowTitle.setText("VER PRODUCTO");
        jPanelTitulo.add(jLabelWindowTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 280, 40));

        jLabelMiniUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconUserMini.png"))); // NOI18N
        jPanelTitulo.add(jLabelMiniUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, 40));

        jLabelUserName.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUserName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Administrador");
        jPanelTitulo.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, 90, -1));

        getContentPane().add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        jPanelLateralD.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLateralD.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLateralD.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanelLateralD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelLateralD, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 150, 100, 430));

        jPanelBotones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBSalir.setBackground(new java.awt.Color(204, 204, 255));
        jBSalir.setText("SALIR");
        jBSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jBSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSalirMouseClicked(evt);
            }
        });
        jPanelBotones.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 120, 40));

        getContentPane().add(jPanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 850, 120));

        jPanelBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFBuscar.setBackground(new java.awt.Color(220, 220, 220));
        jTFBuscar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFBuscar.setForeground(new java.awt.Color(102, 102, 102));
        jTFBuscar.setText("Buscar");
        jTFBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jTFBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFBuscarMouseClicked(evt);
            }
        });
        jPanelBusqueda.add(jTFBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 520, 30));

        jLCodigo.setBackground(new java.awt.Color(0, 0, 0));
        jLCodigo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCodigo.setText("CODIGO");
        jPanelBusqueda.add(jLCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 30));

        jBBuscar.setBackground(new java.awt.Color(0, 0, 0));
        jBBuscar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconSearch.png"))); // NOI18N
        jBBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBuscarMouseClicked(evt);
            }
        });
        jPanelBusqueda.add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, 30));

        getContentPane().add(jPanelBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1050, 80));

        jPanelFormulario.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFormulario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanelFormulario.setForeground(new java.awt.Color(255, 255, 255));
        jPanelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLFecha.setBackground(new java.awt.Color(0, 0, 0));
        jLFecha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFecha.setText("FECHA VENCIMIENTO");
        jPanelFormulario.add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jLDescripcion.setBackground(new java.awt.Color(0, 0, 0));
        jLDescripcion.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDescripcion.setText("DESCRIPCIÓN");
        jPanelFormulario.add(jLDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLPVenta.setBackground(new java.awt.Color(0, 0, 0));
        jLPVenta.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLPVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPVenta.setText("PRECIO VENTA");
        jPanelFormulario.add(jLPVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLCantidad.setBackground(new java.awt.Color(0, 0, 0));
        jLCantidad.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCantidad.setText("CANTIDAD");
        jPanelFormulario.add(jLCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        jImageProducto.setBackground(new java.awt.Color(220, 220, 220));
        jImageProducto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jImageProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImageProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconSoup.png"))); // NOI18N
        jImageProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jImageProducto.setOpaque(true);
        jPanelFormulario.add(jImageProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 250, 220));

        jTFCantidad.setBackground(new java.awt.Color(255, 255, 255));
        jTFCantidad.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCantidad.setForeground(new java.awt.Color(102, 102, 102));
        jTFCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFCantidad.setOpaque(true);
        jPanelFormulario.add(jTFCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 130, 20));

        jSCantidad.setForeground(new java.awt.Color(255, 102, 51));
        jPanelFormulario.add(jSCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 130, 20));

        jTFProveedor.setBackground(new java.awt.Color(255, 255, 255));
        jTFProveedor.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFProveedor.setForeground(new java.awt.Color(102, 102, 102));
        jTFProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFProveedor.setOpaque(true);
        jPanelFormulario.add(jTFProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 370, 30));

        jSDescripcion.setForeground(new java.awt.Color(255, 102, 51));
        jPanelFormulario.add(jSDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 370, 10));

        jTFFecha.setBackground(new java.awt.Color(255, 255, 255));
        jTFFecha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFFecha.setForeground(new java.awt.Color(102, 102, 102));
        jTFFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFFecha.setOpaque(true);
        jPanelFormulario.add(jTFFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 130, 30));

        jSFecha.setForeground(new java.awt.Color(255, 102, 51));
        jPanelFormulario.add(jSFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 130, 10));

        jTFPVenta.setBackground(new java.awt.Color(255, 255, 255));
        jTFPVenta.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFPVenta.setForeground(new java.awt.Color(102, 102, 102));
        jTFPVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFPVenta.setOpaque(true);
        jPanelFormulario.add(jTFPVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 340, 30));

        jSPVenta.setForeground(new java.awt.Color(255, 102, 51));
        jPanelFormulario.add(jSPVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 340, 20));

        jLProveedor.setBackground(new java.awt.Color(0, 0, 0));
        jLProveedor.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLProveedor.setText("PROVEEDOR");
        jPanelFormulario.add(jLProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jSProveedor.setForeground(new java.awt.Color(255, 102, 51));
        jPanelFormulario.add(jSProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 370, 10));

        jTextFieldTipo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTipo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldTipo.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTextFieldTipo.setOpaque(true);
        jPanelFormulario.add(jTextFieldTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 120, 30));

        jSTipo.setForeground(new java.awt.Color(255, 102, 51));
        jPanelFormulario.add(jSTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 120, 10));

        jLTipo.setBackground(new java.awt.Color(0, 0, 0));
        jLTipo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTipo.setText("TIPO");
        jPanelFormulario.add(jLTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLPCompra.setBackground(new java.awt.Color(0, 0, 0));
        jLPCompra.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLPCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPCompra.setText("PRECIO COMPRA");
        jPanelFormulario.add(jLPCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jTFPCompra.setBackground(new java.awt.Color(255, 255, 255));
        jTFPCompra.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFPCompra.setForeground(new java.awt.Color(102, 102, 102));
        jTFPCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFPCompra.setOpaque(true);
        jPanelFormulario.add(jTFPCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 340, 30));

        jSPcompra.setForeground(new java.awt.Color(255, 102, 51));
        jPanelFormulario.add(jSPcompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 340, 20));

        jTFDescrip.setBackground(new java.awt.Color(255, 255, 255));
        jTFDescrip.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFDescrip.setForeground(new java.awt.Color(102, 102, 102));
        jTFDescrip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFDescrip.setOpaque(true);
        jPanelFormulario.add(jTFDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 380, 30));

        getContentPane().add(jPanelFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 850, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalirMouseClicked
        controlMenu.irModuloGInventario(user);
        this.setVisible(false);
    }//GEN-LAST:event_jBSalirMouseClicked
    
    private void mostrarInfoProducto()
    {
        jTFDescrip.setText(product.getDescripcion());
        jTFProveedor.setText(product.getProveedor());
        jTextFieldTipo.setText(product.getTipo());
        jTFFecha.setText(product.getFechaV());
        jTFPCompra.setText(product.getPrecioCompra());
        jTFPVenta.setText(product.getPrecioVenta());
        jTFCantidad.setText(product.getCantidad());

    }
    
    private void borrarInfoCampos()
    {
        jTFBuscar.setText("Buscar");
        jTFDescrip.setText("");
        jTFProveedor.setText("");
        jTextFieldTipo.setText("");
        jTFFecha.setText("");
        jTFPCompra.setText("");
        jTFPVenta.setText("");
        jTFCantidad.setText("");
        
    }
    
    private void jBBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBuscarMouseClicked
      
        product = controlInv.procesarVistaProducto(jTFBuscar.getText());

       if(controlInv.getDatoEncontrado())
       { 
           mostrarInfoProducto();
            
       }else
       {
           borrarInfoCampos();
       }
    }//GEN-LAST:event_jBBuscarMouseClicked

    private void jTFBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFBuscarMouseClicked
        jTFBuscar.setText("");
    }//GEN-LAST:event_jTFBuscarMouseClicked
    
    private Producto product;
    private final ControladorInventario controlInv;
    private final ControladorMenu controlMenu;
    private final Usuario user;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBBuscar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jImageProducto;
    private javax.swing.JLabel jLCantidad;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLPCompra;
    private javax.swing.JLabel jLPVenta;
    private javax.swing.JLabel jLProveedor;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLabelMiniUser1;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelWindowTitle;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelBusqueda;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JPanel jPanelLateralD;
    private javax.swing.JPanel jPanelLateralI;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JSeparator jSCantidad;
    private javax.swing.JSeparator jSDescripcion;
    private javax.swing.JSeparator jSFecha;
    private javax.swing.JSeparator jSPVenta;
    private javax.swing.JSeparator jSPcompra;
    private javax.swing.JSeparator jSProveedor;
    private javax.swing.JSeparator jSTipo;
    private javax.swing.JTextField jTFBuscar;
    private javax.swing.JLabel jTFCantidad;
    private javax.swing.JLabel jTFDescrip;
    private javax.swing.JLabel jTFFecha;
    private javax.swing.JLabel jTFPCompra;
    private javax.swing.JLabel jTFPVenta;
    private javax.swing.JLabel jTFProveedor;
    private javax.swing.JLabel jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
