/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGestionInventario;

import controladorGestionInventario.ControladorInventario;
import controladorGestionUsuario.ControladorMenu;
import modeloGestionInventario.*;
import modeloGestionUsuario.Usuario;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Aidis
 */
public class VentanaRegistroPedido extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public VentanaRegistroPedido(Usuario user) {
        initComponents();
        //Centra la ventana
        this.setLocationRelativeTo(null);
        this.user = user;
        controlInv = new ControladorInventario();
        controlMenu = new ControladorMenu();
        jLabelUserName.setText(user.getNombreUsuario());
        centrarNCamposJTable(jTProductos);
        nroItem =0;
        order =new Pedido();
        items = new ArrayList<>();
        

    }
    private void centrarNCamposJTable(JTable tabla)
    {
        TableCellRenderer rendererFromHeader = tabla.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jLCodigo = new javax.swing.JLabel();
        jAstCodigo = new javax.swing.JLabel();
        jTFcodUsuario = new javax.swing.JTextField();
        jLcodUsuario = new javax.swing.JLabel();
        jAstUsuario = new javax.swing.JLabel();
        jLabelAsterisco5 = new javax.swing.JLabel();
        jBBuscarProducto = new javax.swing.JLabel();
        jSTotal = new javax.swing.JSeparator();
        jLTotal = new javax.swing.JLabel();
        jTFFecha = new javax.swing.JTextField();
        jLFecha = new javax.swing.JLabel();
        jTFCodProducto = new javax.swing.JTextField();
        jLCodProducto = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jAstFecha = new javax.swing.JLabel();
        jLCantidad = new javax.swing.JLabel();
        jAstCantidad = new javax.swing.JLabel();
        jLETotal = new javax.swing.JTextField();
        jBAddProducto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProductos = new javax.swing.JTable();
        jTFCantidad = new javax.swing.JTextField();
        jBRemoveProducto = new javax.swing.JLabel();
        jPanelLateralI = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelWindowTitle = new javax.swing.JLabel();
        jLabelMiniUser1 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();
        jBSalir = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jPanelLateralD = new javax.swing.JPanel();
        jBInformacion = new javax.swing.JLabel();
        jBUno = new javax.swing.JLabel();
        jBDos = new javax.swing.JLabel();
        jBTres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCodigo.setBackground(new java.awt.Color(0, 0, 0));
        jLCodigo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCodigo.setText("CODIGO");
        jPanelMenu.add(jLCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jAstCodigo.setBackground(new java.awt.Color(0, 0, 0));
        jAstCodigo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstCodigo.setForeground(new java.awt.Color(255, 102, 51));
        jAstCodigo.setText("*");
        jPanelMenu.add(jAstCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jTFcodUsuario.setBackground(new java.awt.Color(220, 220, 220));
        jTFcodUsuario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFcodUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jTFcodUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelMenu.add(jTFcodUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 110, 30));

        jLcodUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jLcodUsuario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLcodUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLcodUsuario.setText("ALMACENISTA");
        jPanelMenu.add(jLcodUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        jAstUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jAstUsuario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstUsuario.setForeground(new java.awt.Color(255, 102, 51));
        jAstUsuario.setText("*");
        jPanelMenu.add(jAstUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        jLabelAsterisco5.setBackground(new java.awt.Color(0, 0, 0));
        jLabelAsterisco5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAsterisco5.setForeground(new java.awt.Color(255, 102, 51));
        jLabelAsterisco5.setText("*");
        jPanelMenu.add(jLabelAsterisco5, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 160, 0, -1));

        jBBuscarProducto.setBackground(new java.awt.Color(0, 0, 0));
        jBBuscarProducto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBBuscarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconSearch.png"))); // NOI18N
        jBBuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBuscarProductoMouseClicked(evt);
            }
        });
        jPanelMenu.add(jBBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, 30));

        jSTotal.setForeground(new java.awt.Color(255, 102, 51));
        jPanelMenu.add(jSTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 100, 10));

        jLTotal.setBackground(new java.awt.Color(255, 255, 255));
        jLTotal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLTotal.setForeground(new java.awt.Color(102, 102, 102));
        jLTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTotal.setOpaque(true);
        jPanelMenu.add(jLTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 100, 30));

        jTFFecha.setBackground(new java.awt.Color(220, 220, 220));
        jTFFecha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFFecha.setForeground(new java.awt.Color(102, 102, 102));
        jTFFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelMenu.add(jTFFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 180, 30));

        jLFecha.setBackground(new java.awt.Color(0, 0, 0));
        jLFecha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFecha.setText("FECHA");
        jPanelMenu.add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jTFCodProducto.setBackground(new java.awt.Color(220, 220, 220));
        jTFCodProducto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCodProducto.setForeground(new java.awt.Color(102, 102, 102));
        jTFCodProducto.setText("Buscar");
        jTFCodProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jTFCodProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFCodProductoMouseClicked(evt);
            }
        });
        jPanelMenu.add(jTFCodProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 380, 30));

        jLCodProducto.setBackground(new java.awt.Color(0, 0, 0));
        jLCodProducto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCodProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCodProducto.setText("PRODUCTO");
        jPanelMenu.add(jLCodProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, 30));

        jTFCodigo.setBackground(new java.awt.Color(220, 220, 220));
        jTFCodigo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCodigo.setForeground(new java.awt.Color(102, 102, 102));
        jTFCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelMenu.add(jTFCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 150, 30));

        jAstFecha.setBackground(new java.awt.Color(0, 0, 0));
        jAstFecha.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstFecha.setForeground(new java.awt.Color(255, 102, 51));
        jAstFecha.setText("*");
        jPanelMenu.add(jAstFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 10, -1));

        jLCantidad.setBackground(new java.awt.Color(0, 0, 0));
        jLCantidad.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCantidad.setText("CANTIDAD");
        jPanelMenu.add(jLCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        jAstCantidad.setBackground(new java.awt.Color(0, 0, 0));
        jAstCantidad.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstCantidad.setForeground(new java.awt.Color(255, 102, 51));
        jAstCantidad.setText("*");
        jPanelMenu.add(jAstCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 10, -1));

        jLETotal.setBackground(new java.awt.Color(220, 220, 220));
        jLETotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLETotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLETotal.setText("TOTAL");
        jLETotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelMenu.add(jLETotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 60, 30));

        jBAddProducto.setBackground(new java.awt.Color(0, 0, 0));
        jBAddProducto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBAddProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBAddProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconAddProduct.png"))); // NOI18N
        jBAddProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAddProductoMouseClicked(evt);
            }
        });
        jPanelMenu.add(jBAddProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, -1, 30));

        jScrollPane2.setBackground(new java.awt.Color(220, 220, 220));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jTProductos.setBackground(new java.awt.Color(220, 220, 220));
        jTProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "DESCRIPCIÓN", "PRECIO", "CANTIDAD"
            }
        ));
        jTProductos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTProductos.setFillsViewportHeight(true);
        jTProductos.setGridColor(new java.awt.Color(255, 102, 51));
        jTProductos.setName(""); // NOI18N
        jTProductos.setRowHeight(30);
        jTProductos.setSurrendersFocusOnKeystroke(true);
        jTProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTProductos);

        jPanelMenu.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 770, 200));

        jTFCantidad.setBackground(new java.awt.Color(220, 220, 220));
        jTFCantidad.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCantidad.setForeground(new java.awt.Color(102, 102, 102));
        jTFCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelMenu.add(jTFCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 50, 30));

        jBRemoveProducto.setBackground(new java.awt.Color(0, 0, 0));
        jBRemoveProducto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBRemoveProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBRemoveProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconRemoveProduct.png"))); // NOI18N
        jBRemoveProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBRemoveProductoMouseClicked(evt);
            }
        });
        jPanelMenu.add(jBRemoveProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, -1, 30));

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 850, 430));

        jPanelLateralI.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLateralI.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLateralI.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanelLateralI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelLateralI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, 520));

        jPanelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelWindowTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelWindowTitle.setForeground(new java.awt.Color(255, 102, 51));
        jLabelWindowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWindowTitle.setText("FORMULARIO REGISTRO PEDIDO");
        jPanelTitulo.add(jLabelWindowTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 530, -1));

        jLabelMiniUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconUserMini.png"))); // NOI18N
        jPanelTitulo.add(jLabelMiniUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        jLabelUserName.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUserName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Administrador");
        jPanelTitulo.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 90, -1));

        getContentPane().add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 90));

        jPanelBotones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBSalir.setBackground(new java.awt.Color(204, 204, 255));
        jBSalir.setText("SALIR");
        jBSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jBSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSalirMouseClicked(evt);
            }
        });
        jPanelBotones.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 120, 40));

        jBGuardar.setBackground(new java.awt.Color(204, 204, 255));
        jBGuardar.setText("GUARDAR");
        jBGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jBGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBGuardarMouseClicked(evt);
            }
        });
        jPanelBotones.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, 40));

        getContentPane().add(jPanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 850, 90));

        jPanelLateralD.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLateralD.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLateralD.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanelLateralD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconInformation.png"))); // NOI18N
        jBInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBInformacionMouseClicked(evt);
            }
        });
        jPanelLateralD.add(jBInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jBUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon1.png"))); // NOI18N
        jBUno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBUnoMouseClicked(evt);
            }
        });
        jPanelLateralD.add(jBUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jBDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon2.png"))); // NOI18N
        jBDos.setToolTipText("");
        jBDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBDosMouseClicked(evt);
            }
        });
        jPanelLateralD.add(jBDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jBTres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon3.png"))); // NOI18N
        jBTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTresMouseClicked(evt);
            }
        });
        jPanelLateralD.add(jBTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        getContentPane().add(jPanelLateralD, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, 100, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalirMouseClicked
        controlMenu.irModuloGInventario(user);
        this.setVisible(false);
    }//GEN-LAST:event_jBSalirMouseClicked
    
    private void borrarInfoCampos()
    {
        jTFCodigo.setText("");
        jTFFecha.setText("");
        jTFcodUsuario.setText("");
        jTFCantidad.setText("");
        jTFCodProducto.setText("");
        mostrarTabla(obtenerTablaVacia());
        jLTotal.setText("");
    }
    
    private void tomarInfoPedido()
    {     
        order.setCodigo(jTFCodigo.getText());
        order.setFecha(jTFFecha.getText());
        order.setCodAlmacenista(jTFcodUsuario.getText());
        order.setEstado("Recibido");
    }
    
    private void jBGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGuardarMouseClicked

        tomarInfoPedido();
        controlInv.procesarRegistroPedido(order);
        modificarStockProducto();
        registrarItemsPedido();
        borrarInfoCampos();
        items.clear();
        
    }//GEN-LAST:event_jBGuardarMouseClicked
    
    private void registrarItemsPedido()
    {
        for(int i=0; i< items.size(); i++)
        {
            controlInv.procesarRegistroItemPedido(items.get(i));
            
        }
    }

    private void modificarStockProducto()
    {
        String codigo;
        int totalCantidad, nuevaCant,antiguaCant ;
       for(int i=0; i< items.size(); i++)
       {
            product = new Producto();
            codigo =items.get(i).getCodProducto();
            product =controlInv.procesarVistaProducto(codigo);
           
            antiguaCant = Integer.parseInt(product.getCantidad());
            nuevaCant = (int) items.get(i).getCantidad();
            totalCantidad= antiguaCant + nuevaCant; 
            controlInv. procesarCambioCantidadProducto("cantidad",Integer.toString(totalCantidad),codigo);
       }
    }
    
    private void agregarItemPedido()
    {
        //Registrar Item Pedido
        ItemPedido itemPedido = new ItemPedido();
        nroItem ++;
        itemPedido.setNroItem(Integer.toString(nroItem));
        itemPedido.setCodPedido(jTFCodigo.getText());
        itemPedido.setCodProducto(jTFCodProducto.getText());
        itemPedido.setCantidad(Integer.parseInt(jTFCantidad.getText()));
        items.add(itemPedido);
        
        jTFCodProducto.setText("Buscar");
        jTFCantidad.setText("");
    }
    
    private void quitarItemPedido()
    {
    
        items.remove(nroItem-1);
        jTFCodProducto.setText("Buscar");
        jTFCantidad.setText("");
        nroItem --;
    
    }
    
    private void jBAddProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAddProductoMouseClicked
      
        product.setCantidad(jTFCantidad.getText());  
        
        order.agregarProducto(product);
        
        order.sumarTotalPCompra(); 
        
        agregarItemPedido();
        
        obtenerTablaProductos(order.getProductos());
        
        jLTotal.setText(Double.toString(order.getTotal()));
            
    }//GEN-LAST:event_jBAddProductoMouseClicked
    
    private String [][] obtenerTablaProductosSub(ArrayList<Producto> products, 
                                                                String [][] imp)
    {
        for(int i=0; i< imp.length; i++)
        {
            if(i< products.size())
            {
                imp[i][0]= products.get(i).getCodigo();
                imp[i][1]= products.get(i).getDescripcion();
                imp[i][2]= products.get(i).getPrecioCompra();
                imp[i][3]= products.get(i).getCantidad();
            }else
            {
                imp[i][0]= null;
                imp[i][1]= null;
                imp[i][2]= null;
                imp[i][3]= null;           
             }
        }
        
        return imp;
    }
    
    private void obtenerTablaProductos(ArrayList<Producto> products)
    {
        String imprime[][] = new String [9][4];
        if (products.size()>0)
        {

            imprime = obtenerTablaProductosSub(products, imprime);
        }else
        {
        
            imprime = obtenerTablaVacia();
        
        }
       
         mostrarTabla( imprime);
    }
    
    private void mostrarTabla(String [][] infoTabla)
    {
           jTProductos.setModel(new javax.swing.table.DefaultTableModel(
           infoTabla,
            new String [] {
                "CODIGO", "DESCRIPCIÓN", "PRECIO", "CANTIDAD"
            }
        ));
    
    }
    
    private String [][] obtenerTablaVacia()
    {
         return    new String [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            };
    }
    
    private void jBBuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBuscarProductoMouseClicked
       
       product = controlInv.procesarVistaProducto(jTFCodProducto.getText());
       
       if(controlInv.getDatoEncontrado())
       { 
            jTFCantidad.setText(product.getCantidad());
            System.out.println(product.getCantidad());
            
       }else
       {
           jTFCodProducto.setText("Buscar");

       }
    }//GEN-LAST:event_jBBuscarProductoMouseClicked

    private void jTFCodProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFCodProductoMouseClicked
        jTFCodProducto.setText("");
    }//GEN-LAST:event_jTFCodProductoMouseClicked

    private void jBRemoveProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRemoveProductoMouseClicked
        
        order.quitarProducto(nroItem);
        order.sumarTotalPCompra(); 
        quitarItemPedido();
        obtenerTablaProductos(order.getProductos());
        jLTotal.setText(Double.toString(order.getTotal()));
   
    }//GEN-LAST:event_jBRemoveProductoMouseClicked

    private void jBInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBInformacionMouseClicked
        jTFCodigo.setText("P-004");
        jTFFecha.setText("2020-06-21");
        jTFcodUsuario.setText("A-002");
    }//GEN-LAST:event_jBInformacionMouseClicked

    private void jBUnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBUnoMouseClicked
        jTFCodProducto.setText("USO-001");
    }//GEN-LAST:event_jBUnoMouseClicked

    private void jBDosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDosMouseClicked
       jTFCodProducto.setText("LAT-001");
    }//GEN-LAST:event_jBDosMouseClicked

    private void jBTresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTresMouseClicked
       jTFCodProducto.setText("ETD-001");
    }//GEN-LAST:event_jBTresMouseClicked
    
    
    private final Usuario user;
    private final  Pedido order;
    private Producto product;
    private final ControladorInventario controlInv;
    private final ControladorMenu controlMenu;
    private final ArrayList <ItemPedido> items;
    private int nroItem;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAstCantidad;
    private javax.swing.JLabel jAstCodigo;
    private javax.swing.JLabel jAstFecha;
    private javax.swing.JLabel jAstUsuario;
    private javax.swing.JLabel jBAddProducto;
    private javax.swing.JLabel jBBuscarProducto;
    private javax.swing.JLabel jBDos;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JLabel jBInformacion;
    private javax.swing.JLabel jBRemoveProducto;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jBTres;
    private javax.swing.JLabel jBUno;
    private javax.swing.JLabel jLCantidad;
    private javax.swing.JLabel jLCodProducto;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JTextField jLETotal;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLabelAsterisco5;
    private javax.swing.JLabel jLabelMiniUser1;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelWindowTitle;
    private javax.swing.JLabel jLcodUsuario;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelLateralD;
    private javax.swing.JPanel jPanelLateralI;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JSeparator jSTotal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTextField jTFCodProducto;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFcodUsuario;
    private javax.swing.JTable jTProductos;
    // End of variables declaration//GEN-END:variables
}
