/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGestionUsuario;

import controladorGestionUsuario.ControladorMenu;
import controladorGestionUsuario.ControladorUsuario;
import modeloGestionUsuario.Usuario;


/**
 *
 * @author Aidis
 */
public class VentanaPrincipalUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogin
     */
    public VentanaPrincipalUsuario(Usuario user) {
        initComponents();
        //Centra la ventana
        this.setLocationRelativeTo(null);

        this.user = user;
        controlMenu = new ControladorMenu();
        jLabelUserName.setText(user.getNombreUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jLabelAgregarUsuario = new javax.swing.JLabel();
        jLabelVerUsuario = new javax.swing.JLabel();
        imageFindUser = new javax.swing.JLabel();
        imageAddUser = new javax.swing.JLabel();
        imageEditUser = new javax.swing.JLabel();
        jLabelEditarUsuario1 = new javax.swing.JLabel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelWindowTitle = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        imageExit = new javax.swing.JLabel();
        jLabelMiniUser1 = new javax.swing.JLabel();
        jPaneMenuLateral = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLMenuUsuario = new javax.swing.JLabel();
        jLMenuVenta = new javax.swing.JLabel();
        jLVSoporte = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLMenuReporte = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLMenuInventario = new javax.swing.JLabel();
        jLMenuCliente = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAgregarUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jLabelAgregarUsuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelAgregarUsuario.setForeground(new java.awt.Color(255, 102, 51));
        jLabelAgregarUsuario.setText("REGISTRAR");
        jPanelMenu.add(jLabelAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabelVerUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jLabelVerUsuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelVerUsuario.setForeground(new java.awt.Color(255, 102, 51));
        jLabelVerUsuario.setText("VER");
        jPanelMenu.add(jLabelVerUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, -1, -1));

        imageFindUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageFindUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconFindUser.png"))); // NOI18N
        imageFindUser.setPreferredSize(new java.awt.Dimension(34, 34));
        imageFindUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageFindUserMouseClicked(evt);
            }
        });
        jPanelMenu.add(imageFindUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 150, 130));

        imageAddUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconAddUser.png"))); // NOI18N
        imageAddUser.setPreferredSize(new java.awt.Dimension(34, 34));
        imageAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageAddUserMouseClicked(evt);
            }
        });
        jPanelMenu.add(imageAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 150, 130));

        imageEditUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageEditUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconEditUser.png"))); // NOI18N
        imageEditUser.setPreferredSize(new java.awt.Dimension(34, 34));
        imageEditUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageEditUserMouseClicked(evt);
            }
        });
        jPanelMenu.add(imageEditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 150, 130));

        jLabelEditarUsuario1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelEditarUsuario1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelEditarUsuario1.setForeground(new java.awt.Color(255, 102, 51));
        jLabelEditarUsuario1.setText("EDITAR ");
        jPanelMenu.add(jLabelEditarUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 810, 480));

        jPanelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelWindowTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelWindowTitle.setForeground(new java.awt.Color(255, 102, 51));
        jLabelWindowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWindowTitle.setText("USUARIO");
        jPanelTitulo.add(jLabelWindowTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 160, -1));

        jLabelUserName.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUserName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Administrador");
        jPanelTitulo.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 90, -1));

        imageExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconExit.png"))); // NOI18N
        imageExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageExitMouseClicked(evt);
            }
        });
        jPanelTitulo.add(imageExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, -1));

        jLabelMiniUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconUserMini.png"))); // NOI18N
        jPanelTitulo.add(jLabelMiniUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        getContentPane().add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 100));

        jPaneMenuLateral.setBackground(new java.awt.Color(255, 255, 255));
        jPaneMenuLateral.setForeground(new java.awt.Color(255, 255, 255));
        jPaneMenuLateral.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPaneMenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 253, 1, 10));

        jLMenuUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jLMenuUsuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconMiniUsers .png"))); // NOI18N
        jLMenuUsuario.setText("USUARIO");
        jLMenuUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMenuUsuarioMouseClicked(evt);
            }
        });
        jPaneMenuLateral.add(jLMenuUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 230, -1));

        jLMenuVenta.setBackground(new java.awt.Color(0, 0, 0));
        jLMenuVenta.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLMenuVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconMiniSell.png"))); // NOI18N
        jLMenuVenta.setText("VENTA");
        jLMenuVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMenuVentaMouseClicked(evt);
            }
        });
        jPaneMenuLateral.add(jLMenuVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 230, -1));

        jLVSoporte.setBackground(new java.awt.Color(0, 0, 0));
        jLVSoporte.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLVSoporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconMiniSetting.png"))); // NOI18N
        jLVSoporte.setText("SOPORTE ");
        jLVSoporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLVSoporteMouseClicked(evt);
            }
        });
        jPaneMenuLateral.add(jLVSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 230, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 257, 1, 22));

        jSeparator7.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 10));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator10.setForeground(new java.awt.Color(255, 102, 51));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 238, 10));

        jSeparator4.setForeground(new java.awt.Color(255, 102, 51));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 60, 290, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 102, 51));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 290, 10));

        jPaneMenuLateral.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 10));

        jLMenuReporte.setBackground(new java.awt.Color(0, 0, 0));
        jLMenuReporte.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLMenuReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconMiniForm.png"))); // NOI18N
        jLMenuReporte.setText("REPORTE");
        jLMenuReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMenuReporteMouseClicked(evt);
            }
        });
        jPaneMenuLateral.add(jLMenuReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 230, 26));

        jSeparator11.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 10));

        jSeparator12.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, 10));

        jSeparator13.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 10));

        jLMenuInventario.setBackground(new java.awt.Color(0, 0, 0));
        jLMenuInventario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLMenuInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconMiniInventory.png"))); // NOI18N
        jLMenuInventario.setText("INVENTARIO");
        jLMenuInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMenuInventarioMouseClicked(evt);
            }
        });
        jPaneMenuLateral.add(jLMenuInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 230, 40));

        jLMenuCliente.setBackground(new java.awt.Color(0, 0, 0));
        jLMenuCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconMiniClientes.png"))); // NOI18N
        jLMenuCliente.setText("CLIENTE");
        jLMenuCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMenuClienteMouseClicked(evt);
            }
        });
        jPaneMenuLateral.add(jLMenuCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jSeparator8.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 10));

        jSeparator9.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 10));

        getContentPane().add(jPaneMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageExitMouseClicked
        controlMenu.irVentanaLogin();
        this.setVisible(false);
    }//GEN-LAST:event_imageExitMouseClicked

    private void imageAddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAddUserMouseClicked
        controlMenu.irRegistroUsuario(user );
        this.setVisible(false);
    }//GEN-LAST:event_imageAddUserMouseClicked

    private void imageEditUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageEditUserMouseClicked
        controlMenu.irEdicionUsuario( user);
        this.setVisible(false);
    }//GEN-LAST:event_imageEditUserMouseClicked

    private void imageFindUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageFindUserMouseClicked
        controlMenu.irVistaUsuario( user);
        this.setVisible(false);
    }//GEN-LAST:event_imageFindUserMouseClicked

    private void jLMenuUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMenuUsuarioMouseClicked
        controlMenu.irModuloGUsuario(user);
        this.setVisible(false);
    }//GEN-LAST:event_jLMenuUsuarioMouseClicked

    private void jLMenuVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMenuVentaMouseClicked
        controlMenu.irModuloGVenta(user);
        this.setVisible(false);
    }//GEN-LAST:event_jLMenuVentaMouseClicked

    private void jLVSoporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLVSoporteMouseClicked
        controlMenu.irVentanaSoporte(user);
        this.setVisible(false);
    }//GEN-LAST:event_jLVSoporteMouseClicked

    private void jLMenuReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMenuReporteMouseClicked
        controlMenu.irModuloGReporte(user);
        this.setVisible(false);
    }//GEN-LAST:event_jLMenuReporteMouseClicked

    private void jLMenuInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMenuInventarioMouseClicked
        controlMenu.irModuloGInventario(user);
        this.setVisible(false);
    }//GEN-LAST:event_jLMenuInventarioMouseClicked

    private void jLMenuClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMenuClienteMouseClicked
        controlMenu.irModuloGCliente(user);
        this.setVisible(false);
    }//GEN-LAST:event_jLMenuClienteMouseClicked
    
    private Usuario user;
    private ControladorMenu controlMenu;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageAddUser;
    private javax.swing.JLabel imageEditUser;
    private javax.swing.JLabel imageExit;
    private javax.swing.JLabel imageFindUser;
    private javax.swing.JLabel jLMenuCliente;
    private javax.swing.JLabel jLMenuInventario;
    private javax.swing.JLabel jLMenuReporte;
    private javax.swing.JLabel jLMenuUsuario;
    private javax.swing.JLabel jLMenuVenta;
    private javax.swing.JLabel jLVSoporte;
    private javax.swing.JLabel jLabelAgregarUsuario;
    private javax.swing.JLabel jLabelEditarUsuario1;
    private javax.swing.JLabel jLabelMiniUser1;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelVerUsuario;
    private javax.swing.JLabel jLabelWindowTitle;
    private javax.swing.JPanel jPaneMenuLateral;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
