/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGestionReporte;

import modeloGestionReporte.Reporte;
import controladorGestionReporte.ControladorReporte;
import controladorGestionUsuario.ControladorMenu;
import modeloGestionUsuario.Usuario;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author Aidis
 */
public class VentanaPrincipalReporte extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogin
     */
    public VentanaPrincipalReporte(Usuario user) {
        initComponents();
        //Centra la ventana
        this.setLocationRelativeTo(null);
        this.user = user;
        controlMenu = new ControladorMenu();
        controlReport= new ControladorReporte();
        jLabelUserName.setText(user.getNombreUsuario());
        paneles = new ArrayList<>();
        reportes =new ArrayList<>();
        codigos =new ArrayList<>();
        tipos =new ArrayList<>();
        fechas =new ArrayList<>();

        agregarPaneles();
        agregarCodigos();
        agregarTipos();
        agregarFechas();
        invisivilizarPaneles();
        
        reportes =controlReport.procesarConsultaReportes();
        vilizarPaneles();

    }
    
    private void agregarPaneles()
    {
        paneles.add(jPanelReporte1);
        paneles.add(jPanelReporte2);
        paneles.add(jPanelReporte3);
        paneles.add(jPanelReporte4);
        paneles.add(jPanelReporte5);
        paneles.add(jPanelReporte6);
    }
    
    private void invisivilizarPaneles()
    {
        for (int i=0;i<paneles.size();i++) {
      
             paneles.get(i).setVisible(false);
        }
    }
    
    private void agregarCodigos()
    {
        codigos.add(jTFCodigo1);
        codigos.add(jTFCodigo2);
        codigos.add(jTFCodigo3);
        codigos.add(jTFCodigo4);
        codigos.add(jTFCodigo5);
        codigos.add(jTFCodigo6);
    }
    
    private void agregarTipos()
    {
        tipos.add(jTFTipo1);
        tipos.add(jTFTipo2);
        tipos.add(jTFTipo3);
        tipos.add(jTFTipo4);
        tipos.add(jTFTipo5);
        tipos.add(jTFTipo6);
    
    }
    
    private void agregarFechas()
    {
        fechas.add(jTFFecha1);
        fechas.add(jTFFecha2);
        fechas.add(jTFFecha3);
        fechas.add(jTFFecha4);
        fechas.add(jTFFecha5);
        fechas.add(jTFFecha6);
    }
    
    private void vilizarPaneles()
    {
        for (int i=0;i<reportes.size();i++) {
            codigos.get(i).setText(reportes.get(i).getCodigo());
            tipos.get(i).setText(reportes.get(i).getTipo());
            fechas.get(i).setText(reportes.get(i).getFecha());
            paneles.get(i).setVisible(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabelWindowTitle = new javax.swing.JLabel();
        jLabelMiniUser1 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLExit = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jPanelReporte1 = new javax.swing.JPanel();
        jIconReporte1 = new javax.swing.JLabel();
        jLCodigo = new javax.swing.JLabel();
        jLTipo1 = new javax.swing.JLabel();
        jLFecha1 = new javax.swing.JLabel();
        jSCodigo1 = new javax.swing.JSeparator();
        jTFCodigo1 = new javax.swing.JLabel();
        jTFTipo1 = new javax.swing.JLabel();
        jSCambio1 = new javax.swing.JSeparator();
        jTFFecha1 = new javax.swing.JLabel();
        jSFecha1 = new javax.swing.JSeparator();
        jPanelReporte2 = new javax.swing.JPanel();
        jIconReporte2 = new javax.swing.JLabel();
        jLCodigo2 = new javax.swing.JLabel();
        jLTipo2 = new javax.swing.JLabel();
        jLFecha2 = new javax.swing.JLabel();
        jSCodigo2 = new javax.swing.JSeparator();
        jTFCodigo2 = new javax.swing.JLabel();
        jTFTipo2 = new javax.swing.JLabel();
        jSTipo2 = new javax.swing.JSeparator();
        jTFFecha2 = new javax.swing.JLabel();
        jSFecha2 = new javax.swing.JSeparator();
        jPanelReporte3 = new javax.swing.JPanel();
        jIconReporte3 = new javax.swing.JLabel();
        jLCodigo3 = new javax.swing.JLabel();
        jLTipo3 = new javax.swing.JLabel();
        jLFecha3 = new javax.swing.JLabel();
        jSCodigo3 = new javax.swing.JSeparator();
        jTFCodigo3 = new javax.swing.JLabel();
        jTFTipo3 = new javax.swing.JLabel();
        jSTipo3 = new javax.swing.JSeparator();
        jTFFecha3 = new javax.swing.JLabel();
        jSFecha3 = new javax.swing.JSeparator();
        jPanelReporte6 = new javax.swing.JPanel();
        jIconReporte6 = new javax.swing.JLabel();
        jLCodigo6 = new javax.swing.JLabel();
        jLTipo6 = new javax.swing.JLabel();
        jLFecha6 = new javax.swing.JLabel();
        jSCodigo6 = new javax.swing.JSeparator();
        jTFCodigo6 = new javax.swing.JLabel();
        jTFTipo6 = new javax.swing.JLabel();
        jSTipo6 = new javax.swing.JSeparator();
        jTFFecha6 = new javax.swing.JLabel();
        jSFecha6 = new javax.swing.JSeparator();
        jPanelReporte4 = new javax.swing.JPanel();
        jIconReporte4 = new javax.swing.JLabel();
        jLCodigo4 = new javax.swing.JLabel();
        jLTipo4 = new javax.swing.JLabel();
        jLFecha4 = new javax.swing.JLabel();
        jSCodigo4 = new javax.swing.JSeparator();
        jTFCodigo4 = new javax.swing.JLabel();
        jTFTipo4 = new javax.swing.JLabel();
        jSTipo4 = new javax.swing.JSeparator();
        jTFFecha4 = new javax.swing.JLabel();
        jSFecha4 = new javax.swing.JSeparator();
        jPanelReporte5 = new javax.swing.JPanel();
        jIconReporte5 = new javax.swing.JLabel();
        jLCodigo5 = new javax.swing.JLabel();
        jLTipo5 = new javax.swing.JLabel();
        jLFecha5 = new javax.swing.JLabel();
        jSCodigo5 = new javax.swing.JSeparator();
        jTFCodigo5 = new javax.swing.JLabel();
        jTFTipo5 = new javax.swing.JLabel();
        jSTipo5 = new javax.swing.JSeparator();
        jTFFecha5 = new javax.swing.JLabel();
        jSFecha5 = new javax.swing.JSeparator();
        jPanelLateralI = new javax.swing.JPanel();
        jLMUsuario = new javax.swing.JLabel();
        jLMVenta = new javax.swing.JLabel();
        jLMSoporte = new javax.swing.JLabel();
        jSUsuarioVenta = new javax.swing.JSeparator();
        jSCliente = new javax.swing.JSeparator();
        jLMReporte = new javax.swing.JLabel();
        jSClienteInventario = new javax.swing.JSeparator();
        jSoporteInventario = new javax.swing.JSeparator();
        jSoporteUsuario = new javax.swing.JSeparator();
        jLMInventario = new javax.swing.JLabel();
        jLMCliente = new javax.swing.JLabel();
        jSReporte = new javax.swing.JSeparator();
        jSVentaSoporte = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelWindowTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelWindowTitle.setForeground(new java.awt.Color(255, 102, 51));
        jLabelWindowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWindowTitle.setText("REPORTE");
        jPanelTitulo.add(jLabelWindowTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabelMiniUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconUserMini.png"))); // NOI18N
        jPanelTitulo.add(jLabelMiniUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        jLabelUserName.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUserName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Administrador");
        jPanelTitulo.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 90, -1));

        jLExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconExit.png"))); // NOI18N
        jLExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLExitMouseClicked(evt);
            }
        });
        jPanelTitulo.add(jLExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, -1));

        getContentPane().add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 100));

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelReporte1.setBackground(new java.awt.Color(220, 220, 220));
        jPanelReporte1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelReporte1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jIconReporte1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jIconReporte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconReportCard.png"))); // NOI18N
        jIconReporte1.setPreferredSize(new java.awt.Dimension(34, 34));
        jIconReporte1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jIconReporte1MouseClicked(evt);
            }
        });
        jPanelReporte1.add(jIconReporte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLCodigo.setBackground(new java.awt.Color(0, 0, 0));
        jLCodigo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCodigo.setText("COD");
        jPanelReporte1.add(jLCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        jLTipo1.setBackground(new java.awt.Color(0, 0, 0));
        jLTipo1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLTipo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTipo1.setText("TIPO");
        jPanelReporte1.add(jLTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 30));

        jLFecha1.setBackground(new java.awt.Color(0, 0, 0));
        jLFecha1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLFecha1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFecha1.setText("FECHA");
        jPanelReporte1.add(jLFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 30));

        jSCodigo1.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte1.add(jSCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 80, 10));

        jTFCodigo1.setBackground(new java.awt.Color(255, 255, 255));
        jTFCodigo1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCodigo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFCodigo1.setText("R-001");
        jTFCodigo1.setOpaque(true);
        jPanelReporte1.add(jTFCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 80, 30));

        jTFTipo1.setBackground(new java.awt.Color(255, 255, 255));
        jTFTipo1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFTipo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFTipo1.setText("Cambio");
        jTFTipo1.setOpaque(true);
        jPanelReporte1.add(jTFTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, 30));

        jSCambio1.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte1.add(jSCambio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, 10));

        jTFFecha1.setBackground(new java.awt.Color(255, 255, 255));
        jTFFecha1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFFecha1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFFecha1.setText("25/10/2020");
        jTFFecha1.setOpaque(true);
        jPanelReporte1.add(jTFFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 120, 30));

        jSFecha1.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte1.add(jSFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 120, 10));

        jPanelMenu.add(jPanelReporte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 620, 50));

        jPanelReporte2.setBackground(new java.awt.Color(220, 220, 220));
        jPanelReporte2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelReporte2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jIconReporte2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jIconReporte2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconReportCard.png"))); // NOI18N
        jIconReporte2.setPreferredSize(new java.awt.Dimension(34, 34));
        jIconReporte2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jIconReporte2MouseClicked(evt);
            }
        });
        jPanelReporte2.add(jIconReporte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLCodigo2.setBackground(new java.awt.Color(0, 0, 0));
        jLCodigo2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCodigo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCodigo2.setText("COD");
        jPanelReporte2.add(jLCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        jLTipo2.setBackground(new java.awt.Color(0, 0, 0));
        jLTipo2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLTipo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTipo2.setText("TIPO");
        jPanelReporte2.add(jLTipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 30));

        jLFecha2.setBackground(new java.awt.Color(0, 0, 0));
        jLFecha2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLFecha2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFecha2.setText("FECHA");
        jPanelReporte2.add(jLFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 30));

        jSCodigo2.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte2.add(jSCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 80, 10));

        jTFCodigo2.setBackground(new java.awt.Color(255, 255, 255));
        jTFCodigo2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCodigo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFCodigo2.setText("R-002");
        jTFCodigo2.setOpaque(true);
        jPanelReporte2.add(jTFCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 80, 30));

        jTFTipo2.setBackground(new java.awt.Color(255, 255, 255));
        jTFTipo2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFTipo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFTipo2.setText("Averia");
        jTFTipo2.setOpaque(true);
        jPanelReporte2.add(jTFTipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, 30));

        jSTipo2.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte2.add(jSTipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, 10));

        jTFFecha2.setBackground(new java.awt.Color(255, 255, 255));
        jTFFecha2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFFecha2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFFecha2.setText("25/09/2020");
        jTFFecha2.setOpaque(true);
        jPanelReporte2.add(jTFFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 120, 30));

        jSFecha2.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte2.add(jSFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 120, 10));

        jPanelMenu.add(jPanelReporte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 620, 50));

        jPanelReporte3.setBackground(new java.awt.Color(220, 220, 220));
        jPanelReporte3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelReporte3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jIconReporte3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jIconReporte3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconReportCard.png"))); // NOI18N
        jIconReporte3.setPreferredSize(new java.awt.Dimension(34, 34));
        jIconReporte3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jIconReporte3MouseClicked(evt);
            }
        });
        jPanelReporte3.add(jIconReporte3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLCodigo3.setBackground(new java.awt.Color(0, 0, 0));
        jLCodigo3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCodigo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCodigo3.setText("COD");
        jPanelReporte3.add(jLCodigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        jLTipo3.setBackground(new java.awt.Color(0, 0, 0));
        jLTipo3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLTipo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTipo3.setText("TIPO");
        jPanelReporte3.add(jLTipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 30));

        jLFecha3.setBackground(new java.awt.Color(0, 0, 0));
        jLFecha3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLFecha3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFecha3.setText("FECHA");
        jPanelReporte3.add(jLFecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 30));

        jSCodigo3.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte3.add(jSCodigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 80, 10));

        jTFCodigo3.setBackground(new java.awt.Color(255, 255, 255));
        jTFCodigo3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCodigo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFCodigo3.setText("R-001");
        jTFCodigo3.setOpaque(true);
        jPanelReporte3.add(jTFCodigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 80, 30));

        jTFTipo3.setBackground(new java.awt.Color(255, 255, 255));
        jTFTipo3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFTipo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFTipo3.setText("Cambio");
        jTFTipo3.setOpaque(true);
        jPanelReporte3.add(jTFTipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, 30));

        jSTipo3.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte3.add(jSTipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, 10));

        jTFFecha3.setBackground(new java.awt.Color(255, 255, 255));
        jTFFecha3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFFecha3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFFecha3.setText("25/10/2020");
        jTFFecha3.setOpaque(true);
        jPanelReporte3.add(jTFFecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 120, 30));

        jSFecha3.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte3.add(jSFecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 120, 10));

        jPanelMenu.add(jPanelReporte3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 620, 50));

        jPanelReporte6.setBackground(new java.awt.Color(220, 220, 220));
        jPanelReporte6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelReporte6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jIconReporte6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jIconReporte6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconReportCard.png"))); // NOI18N
        jIconReporte6.setPreferredSize(new java.awt.Dimension(34, 34));
        jIconReporte6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jIconReporte6MouseClicked(evt);
            }
        });
        jPanelReporte6.add(jIconReporte6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLCodigo6.setBackground(new java.awt.Color(0, 0, 0));
        jLCodigo6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCodigo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCodigo6.setText("COD");
        jPanelReporte6.add(jLCodigo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        jLTipo6.setBackground(new java.awt.Color(0, 0, 0));
        jLTipo6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLTipo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTipo6.setText("TIPO");
        jPanelReporte6.add(jLTipo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 30));

        jLFecha6.setBackground(new java.awt.Color(0, 0, 0));
        jLFecha6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLFecha6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFecha6.setText("FECHA");
        jPanelReporte6.add(jLFecha6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 30));

        jSCodigo6.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte6.add(jSCodigo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 80, 10));

        jTFCodigo6.setBackground(new java.awt.Color(255, 255, 255));
        jTFCodigo6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCodigo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFCodigo6.setText("R-001");
        jTFCodigo6.setOpaque(true);
        jPanelReporte6.add(jTFCodigo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 80, 30));

        jTFTipo6.setBackground(new java.awt.Color(255, 255, 255));
        jTFTipo6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFTipo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFTipo6.setText("Cambio");
        jTFTipo6.setOpaque(true);
        jPanelReporte6.add(jTFTipo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, 30));

        jSTipo6.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte6.add(jSTipo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, 10));

        jTFFecha6.setBackground(new java.awt.Color(255, 255, 255));
        jTFFecha6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFFecha6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFFecha6.setText("25/10/2020");
        jTFFecha6.setOpaque(true);
        jPanelReporte6.add(jTFFecha6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 120, 30));

        jSFecha6.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte6.add(jSFecha6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 120, 10));

        jPanelMenu.add(jPanelReporte6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 620, 50));

        jPanelReporte4.setBackground(new java.awt.Color(220, 220, 220));
        jPanelReporte4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelReporte4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jIconReporte4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jIconReporte4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconReportCard.png"))); // NOI18N
        jIconReporte4.setPreferredSize(new java.awt.Dimension(34, 34));
        jIconReporte4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jIconReporte4MouseClicked(evt);
            }
        });
        jPanelReporte4.add(jIconReporte4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLCodigo4.setBackground(new java.awt.Color(0, 0, 0));
        jLCodigo4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCodigo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCodigo4.setText("COD");
        jPanelReporte4.add(jLCodigo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        jLTipo4.setBackground(new java.awt.Color(0, 0, 0));
        jLTipo4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLTipo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTipo4.setText("TIPO");
        jPanelReporte4.add(jLTipo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 30));

        jLFecha4.setBackground(new java.awt.Color(0, 0, 0));
        jLFecha4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLFecha4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFecha4.setText("FECHA");
        jPanelReporte4.add(jLFecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 30));

        jSCodigo4.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte4.add(jSCodigo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 80, 10));

        jTFCodigo4.setBackground(new java.awt.Color(255, 255, 255));
        jTFCodigo4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCodigo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFCodigo4.setText("R-001");
        jTFCodigo4.setOpaque(true);
        jPanelReporte4.add(jTFCodigo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 80, 30));

        jTFTipo4.setBackground(new java.awt.Color(255, 255, 255));
        jTFTipo4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFTipo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFTipo4.setText("Cambio");
        jTFTipo4.setOpaque(true);
        jPanelReporte4.add(jTFTipo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, 30));

        jSTipo4.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte4.add(jSTipo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, 10));

        jTFFecha4.setBackground(new java.awt.Color(255, 255, 255));
        jTFFecha4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFFecha4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFFecha4.setText("25/10/2020");
        jTFFecha4.setOpaque(true);
        jPanelReporte4.add(jTFFecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 120, 30));

        jSFecha4.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte4.add(jSFecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 120, 10));

        jPanelMenu.add(jPanelReporte4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 620, 50));

        jPanelReporte5.setBackground(new java.awt.Color(220, 220, 220));
        jPanelReporte5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelReporte5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jIconReporte5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jIconReporte5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconReportCard.png"))); // NOI18N
        jIconReporte5.setPreferredSize(new java.awt.Dimension(34, 34));
        jIconReporte5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jIconReporte5MouseClicked(evt);
            }
        });
        jPanelReporte5.add(jIconReporte5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLCodigo5.setBackground(new java.awt.Color(0, 0, 0));
        jLCodigo5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCodigo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCodigo5.setText("COD");
        jPanelReporte5.add(jLCodigo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        jLTipo5.setBackground(new java.awt.Color(0, 0, 0));
        jLTipo5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLTipo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTipo5.setText("TIPO");
        jPanelReporte5.add(jLTipo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 30));

        jLFecha5.setBackground(new java.awt.Color(0, 0, 0));
        jLFecha5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLFecha5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFecha5.setText("FECHA");
        jPanelReporte5.add(jLFecha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 30));

        jSCodigo5.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte5.add(jSCodigo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 80, 10));

        jTFCodigo5.setBackground(new java.awt.Color(255, 255, 255));
        jTFCodigo5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCodigo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFCodigo5.setText("R-001");
        jTFCodigo5.setOpaque(true);
        jPanelReporte5.add(jTFCodigo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 80, 30));

        jTFTipo5.setBackground(new java.awt.Color(255, 255, 255));
        jTFTipo5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFTipo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFTipo5.setText("Cambio");
        jTFTipo5.setOpaque(true);
        jPanelReporte5.add(jTFTipo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, 30));

        jSTipo5.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte5.add(jSTipo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, 10));

        jTFFecha5.setBackground(new java.awt.Color(255, 255, 255));
        jTFFecha5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFFecha5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFFecha5.setText("25/10/2020");
        jTFFecha5.setOpaque(true);
        jPanelReporte5.add(jTFFecha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 120, 30));

        jSFecha5.setForeground(new java.awt.Color(255, 102, 51));
        jPanelReporte5.add(jSFecha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 120, 10));

        jPanelMenu.add(jPanelReporte5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 620, 50));

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 810, 480));

        jPanelLateralI.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLateralI.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLateralI.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanelLateralI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLMUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jLMUsuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLMUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconMiniUsers .png"))); // NOI18N
        jLMUsuario.setText("USUARIO");
        jLMUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMUsuarioMouseClicked(evt);
            }
        });
        jPanelLateralI.add(jLMUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 230, -1));

        jLMVenta.setBackground(new java.awt.Color(0, 0, 0));
        jLMVenta.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLMVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconMiniSell.png"))); // NOI18N
        jLMVenta.setText("VENTA");
        jLMVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMVentaMouseClicked(evt);
            }
        });
        jPanelLateralI.add(jLMVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 230, -1));

        jLMSoporte.setBackground(new java.awt.Color(0, 0, 0));
        jLMSoporte.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLMSoporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconMiniSetting.png"))); // NOI18N
        jLMSoporte.setText("SOPORTE ");
        jLMSoporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMSoporteMouseClicked(evt);
            }
        });
        jPanelLateralI.add(jLMSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 230, -1));

        jSUsuarioVenta.setForeground(new java.awt.Color(255, 102, 51));
        jPanelLateralI.add(jSUsuarioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 10));

        jSCliente.setForeground(new java.awt.Color(255, 102, 51));
        jPanelLateralI.add(jSCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 238, 10));

        jLMReporte.setBackground(new java.awt.Color(0, 0, 0));
        jLMReporte.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLMReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconMiniForm.png"))); // NOI18N
        jLMReporte.setText("REPORTE");
        jLMReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMReporteMouseClicked(evt);
            }
        });
        jPanelLateralI.add(jLMReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, 230, 40));

        jSClienteInventario.setForeground(new java.awt.Color(255, 102, 51));
        jPanelLateralI.add(jSClienteInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 10));

        jSoporteInventario.setForeground(new java.awt.Color(255, 102, 51));
        jPanelLateralI.add(jSoporteInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, 10));

        jSoporteUsuario.setForeground(new java.awt.Color(255, 102, 51));
        jPanelLateralI.add(jSoporteUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 10));

        jLMInventario.setBackground(new java.awt.Color(0, 0, 0));
        jLMInventario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLMInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconMiniInventory.png"))); // NOI18N
        jLMInventario.setText("INVENTARIO");
        jLMInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMInventarioMouseClicked(evt);
            }
        });
        jPanelLateralI.add(jLMInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 230, 40));

        jLMCliente.setBackground(new java.awt.Color(0, 0, 0));
        jLMCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLMCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconMiniClientes.png"))); // NOI18N
        jLMCliente.setText("CLIENTE");
        jLMCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMClienteMouseClicked(evt);
            }
        });
        jPanelLateralI.add(jLMCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jSReporte.setForeground(new java.awt.Color(255, 102, 51));
        jPanelLateralI.add(jSReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 10));

        jSVentaSoporte.setForeground(new java.awt.Color(255, 102, 51));
        jPanelLateralI.add(jSVentaSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 10));

        getContentPane().add(jPanelLateralI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jIconReporte1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIconReporte1MouseClicked
        controlReport.irVistaCliente(user, reportes.get(0));
        this.setVisible(false);
    }//GEN-LAST:event_jIconReporte1MouseClicked

    private void jIconReporte2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIconReporte2MouseClicked
        controlReport.irVistaCliente(user, reportes.get(1));
        this.setVisible(false);
    }//GEN-LAST:event_jIconReporte2MouseClicked

    private void jIconReporte3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIconReporte3MouseClicked
        controlReport.irVistaCliente(user, reportes.get(2));
        this.setVisible(false);    
    }//GEN-LAST:event_jIconReporte3MouseClicked

    private void jIconReporte6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIconReporte6MouseClicked
        controlReport.irVistaCliente(user, reportes.get(5));
        this.setVisible(false);
    }//GEN-LAST:event_jIconReporte6MouseClicked

    private void jIconReporte4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIconReporte4MouseClicked
        controlReport.irVistaCliente(user,reportes.get(3));
        this.setVisible(false);
    }//GEN-LAST:event_jIconReporte4MouseClicked

    private void jIconReporte5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIconReporte5MouseClicked
        controlReport.irVistaCliente(user, reportes.get(4));
        this.setVisible(false); 
    }//GEN-LAST:event_jIconReporte5MouseClicked

    private void jLExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitMouseClicked
        controlMenu.irVentanaLogin();
        this.setVisible(false);
    }//GEN-LAST:event_jLExitMouseClicked

    private void jLMUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMUsuarioMouseClicked
        controlMenu.irModuloGUsuario(user);
        this.setVisible(false);
    }//GEN-LAST:event_jLMUsuarioMouseClicked

    private void jLMVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMVentaMouseClicked
        controlMenu.irModuloGVenta(user);
        this.setVisible(false);
    }//GEN-LAST:event_jLMVentaMouseClicked

    private void jLMSoporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMSoporteMouseClicked
        controlMenu.irVentanaSoporte(user);
        this.setVisible(false);
    }//GEN-LAST:event_jLMSoporteMouseClicked

    private void jLMReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMReporteMouseClicked
        controlMenu.irModuloGReporte(user);
        this.setVisible(false);
    }//GEN-LAST:event_jLMReporteMouseClicked

    private void jLMInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMInventarioMouseClicked
        controlMenu.irModuloGInventario(user);
        this.setVisible(false);
    }//GEN-LAST:event_jLMInventarioMouseClicked

    private void jLMClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMClienteMouseClicked
        controlMenu.irModuloGCliente(user);
        this.setVisible(false);
    }//GEN-LAST:event_jLMClienteMouseClicked

    private final Usuario user;
    private final ControladorMenu controlMenu;
    private ArrayList <Reporte> reportes;
    private final ArrayList <JPanel> paneles;
    private final ArrayList <JLabel> codigos;
    private final ArrayList <JLabel> tipos;
    private final ArrayList <JLabel> fechas;
    private final ControladorReporte controlReport;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jIconReporte1;
    private javax.swing.JLabel jIconReporte2;
    private javax.swing.JLabel jIconReporte3;
    private javax.swing.JLabel jIconReporte4;
    private javax.swing.JLabel jIconReporte5;
    private javax.swing.JLabel jIconReporte6;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLCodigo2;
    private javax.swing.JLabel jLCodigo3;
    private javax.swing.JLabel jLCodigo4;
    private javax.swing.JLabel jLCodigo5;
    private javax.swing.JLabel jLCodigo6;
    private javax.swing.JLabel jLExit;
    private javax.swing.JLabel jLFecha1;
    private javax.swing.JLabel jLFecha2;
    private javax.swing.JLabel jLFecha3;
    private javax.swing.JLabel jLFecha4;
    private javax.swing.JLabel jLFecha5;
    private javax.swing.JLabel jLFecha6;
    private javax.swing.JLabel jLMCliente;
    private javax.swing.JLabel jLMInventario;
    private javax.swing.JLabel jLMReporte;
    private javax.swing.JLabel jLMSoporte;
    private javax.swing.JLabel jLMUsuario;
    private javax.swing.JLabel jLMVenta;
    private javax.swing.JLabel jLTipo1;
    private javax.swing.JLabel jLTipo2;
    private javax.swing.JLabel jLTipo3;
    private javax.swing.JLabel jLTipo4;
    private javax.swing.JLabel jLTipo5;
    private javax.swing.JLabel jLTipo6;
    private javax.swing.JLabel jLabelMiniUser1;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelWindowTitle;
    private javax.swing.JPanel jPanelLateralI;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelReporte1;
    private javax.swing.JPanel jPanelReporte2;
    private javax.swing.JPanel jPanelReporte3;
    private javax.swing.JPanel jPanelReporte4;
    private javax.swing.JPanel jPanelReporte5;
    private javax.swing.JPanel jPanelReporte6;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JSeparator jSCambio1;
    private javax.swing.JSeparator jSCliente;
    private javax.swing.JSeparator jSClienteInventario;
    private javax.swing.JSeparator jSCodigo1;
    private javax.swing.JSeparator jSCodigo2;
    private javax.swing.JSeparator jSCodigo3;
    private javax.swing.JSeparator jSCodigo4;
    private javax.swing.JSeparator jSCodigo5;
    private javax.swing.JSeparator jSCodigo6;
    private javax.swing.JSeparator jSFecha1;
    private javax.swing.JSeparator jSFecha2;
    private javax.swing.JSeparator jSFecha3;
    private javax.swing.JSeparator jSFecha4;
    private javax.swing.JSeparator jSFecha5;
    private javax.swing.JSeparator jSFecha6;
    private javax.swing.JSeparator jSReporte;
    private javax.swing.JSeparator jSTipo2;
    private javax.swing.JSeparator jSTipo3;
    private javax.swing.JSeparator jSTipo4;
    private javax.swing.JSeparator jSTipo5;
    private javax.swing.JSeparator jSTipo6;
    private javax.swing.JSeparator jSUsuarioVenta;
    private javax.swing.JSeparator jSVentaSoporte;
    private javax.swing.JSeparator jSoporteInventario;
    private javax.swing.JSeparator jSoporteUsuario;
    private javax.swing.JLabel jTFCodigo1;
    private javax.swing.JLabel jTFCodigo2;
    private javax.swing.JLabel jTFCodigo3;
    private javax.swing.JLabel jTFCodigo4;
    private javax.swing.JLabel jTFCodigo5;
    private javax.swing.JLabel jTFCodigo6;
    private javax.swing.JLabel jTFFecha1;
    private javax.swing.JLabel jTFFecha2;
    private javax.swing.JLabel jTFFecha3;
    private javax.swing.JLabel jTFFecha4;
    private javax.swing.JLabel jTFFecha5;
    private javax.swing.JLabel jTFFecha6;
    private javax.swing.JLabel jTFTipo1;
    private javax.swing.JLabel jTFTipo2;
    private javax.swing.JLabel jTFTipo3;
    private javax.swing.JLabel jTFTipo4;
    private javax.swing.JLabel jTFTipo5;
    private javax.swing.JLabel jTFTipo6;
    // End of variables declaration//GEN-END:variables
}
