/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGestionReporte;


import controladorGestionInventario.*;
import modeloGestionInventario.*;
import controladorGestionReporte.*;
import controladorGestionUsuario.*;
import modeloGestionReporte.*;
import modeloGestionUsuario.*;


/**
 *
 * @author Aidis
 */
public class VentanaReporteAveriaProducto extends javax.swing.JFrame {

    /**
     * Creates new form Login
     * @param user
     */
    public VentanaReporteAveriaProducto(Usuario user) {
       initComponents();
        //Centra la ventana
        this.setLocationRelativeTo(null);
        this.user = user;
        controlReport= new ControladorReporte();
        controlMenu = new ControladorMenu();
        jLabelUserName.setText(user.getNombreUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFormulario = new javax.swing.JPanel();
        jLCodigo = new javax.swing.JLabel();
        jAstCodigo = new javax.swing.JLabel();
        jTFAlmacenista = new javax.swing.JTextField();
        jLUsuario = new javax.swing.JLabel();
        jAstTipo = new javax.swing.JLabel();
        jLProveedor = new javax.swing.JLabel();
        jBAddProducto = new javax.swing.JLabel();
        jTFTipo = new javax.swing.JTextField();
        jLFecha = new javax.swing.JLabel();
        jAstFecha = new javax.swing.JLabel();
        jTFCProduct = new javax.swing.JTextField();
        jLProducto = new javax.swing.JLabel();
        jSProveedor = new javax.swing.JSeparator();
        jTFProveedor = new javax.swing.JLabel();
        jLComentarios = new javax.swing.JLabel();
        jTFDescripProducto = new javax.swing.JLabel();
        jSDProducto = new javax.swing.JSeparator();
        jLTipo = new javax.swing.JLabel();
        jAstComentario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAComentario = new javax.swing.JTextArea();
        jLDProducto = new javax.swing.JLabel();
        jTFFecha = new javax.swing.JTextField();
        jAstUsuario = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jPanelLateralI = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelWindowTitle = new javax.swing.JLabel();
        jLabelMiniUser1 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jPanelLateralD = new javax.swing.JPanel();
        jBInformacion = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();
        jBSalir = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFormulario.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFormulario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanelFormulario.setForeground(new java.awt.Color(255, 255, 255));
        jPanelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCodigo.setBackground(new java.awt.Color(0, 0, 0));
        jLCodigo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCodigo.setText("CODIGO");
        jPanelFormulario.add(jLCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jAstCodigo.setBackground(new java.awt.Color(0, 0, 0));
        jAstCodigo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstCodigo.setForeground(new java.awt.Color(255, 102, 51));
        jAstCodigo.setText("*");
        jPanelFormulario.add(jAstCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jTFAlmacenista.setBackground(new java.awt.Color(220, 220, 220));
        jTFAlmacenista.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFAlmacenista.setForeground(new java.awt.Color(102, 102, 102));
        jTFAlmacenista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelFormulario.add(jTFAlmacenista, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 80, 30));

        jLUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jLUsuario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLUsuario.setText("ALMACENISTA");
        jPanelFormulario.add(jLUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        jAstTipo.setBackground(new java.awt.Color(0, 0, 0));
        jAstTipo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstTipo.setForeground(new java.awt.Color(255, 102, 51));
        jAstTipo.setText("*");
        jPanelFormulario.add(jAstTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 10, -1));

        jLProveedor.setBackground(new java.awt.Color(0, 0, 0));
        jLProveedor.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLProveedor.setText("PROVEEDOR ");
        jPanelFormulario.add(jLProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jBAddProducto.setBackground(new java.awt.Color(0, 0, 0));
        jBAddProducto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBAddProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBAddProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconAddProduct.png"))); // NOI18N
        jBAddProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAddProductoMouseClicked(evt);
            }
        });
        jPanelFormulario.add(jBAddProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, 30));

        jTFTipo.setBackground(new java.awt.Color(220, 220, 220));
        jTFTipo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFTipo.setForeground(new java.awt.Color(255, 255, 255));
        jTFTipo.setText("Averia");
        jTFTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jTFTipo.setEnabled(false);
        jPanelFormulario.add(jTFTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 70, 20));

        jLFecha.setBackground(new java.awt.Color(0, 0, 0));
        jLFecha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFecha.setText("FECHA");
        jPanelFormulario.add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jAstFecha.setBackground(new java.awt.Color(0, 0, 0));
        jAstFecha.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstFecha.setForeground(new java.awt.Color(255, 102, 51));
        jAstFecha.setText("*");
        jPanelFormulario.add(jAstFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jTFCProduct.setBackground(new java.awt.Color(220, 220, 220));
        jTFCProduct.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCProduct.setForeground(new java.awt.Color(102, 102, 102));
        jTFCProduct.setText("Buscar");
        jTFCProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jTFCProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFCProductMouseClicked(evt);
            }
        });
        jPanelFormulario.add(jTFCProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 390, 30));

        jLProducto.setBackground(new java.awt.Color(0, 0, 0));
        jLProducto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLProducto.setText("PRODUCTO");
        jPanelFormulario.add(jLProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 90, 30));

        jSProveedor.setForeground(new java.awt.Color(255, 102, 51));
        jPanelFormulario.add(jSProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 370, 10));

        jTFProveedor.setBackground(new java.awt.Color(255, 255, 255));
        jTFProveedor.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFProveedor.setForeground(new java.awt.Color(102, 102, 102));
        jTFProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFProveedor.setOpaque(true);
        jPanelFormulario.add(jTFProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 370, 30));

        jLComentarios.setBackground(new java.awt.Color(0, 0, 0));
        jLComentarios.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLComentarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLComentarios.setText("COMENTARIOS");
        jPanelFormulario.add(jLComentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jTFDescripProducto.setBackground(new java.awt.Color(255, 255, 255));
        jTFDescripProducto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFDescripProducto.setForeground(new java.awt.Color(102, 102, 102));
        jTFDescripProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFDescripProducto.setOpaque(true);
        jPanelFormulario.add(jTFDescripProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 360, 30));

        jSDProducto.setForeground(new java.awt.Color(255, 102, 51));
        jPanelFormulario.add(jSDProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 360, 10));

        jLTipo.setBackground(new java.awt.Color(0, 0, 0));
        jLTipo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTipo.setText("TIPO");
        jPanelFormulario.add(jLTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, -1, -1));

        jAstComentario.setBackground(new java.awt.Color(0, 0, 0));
        jAstComentario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstComentario.setForeground(new java.awt.Color(255, 102, 51));
        jAstComentario.setText("*");
        jPanelFormulario.add(jAstComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 10, -1));

        jTAComentario.setBackground(new java.awt.Color(220, 220, 220));
        jTAComentario.setColumns(20);
        jTAComentario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTAComentario.setForeground(new java.awt.Color(102, 102, 102));
        jTAComentario.setRows(5);
        jTAComentario.setText("Explique brevemente la averia del producto...");
        jTAComentario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jTAComentario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTAComentarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTAComentario);

        jPanelFormulario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 650, 130));

        jLDProducto.setBackground(new java.awt.Color(0, 0, 0));
        jLDProducto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLDProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDProducto.setText("DESCRIPCIÓN");
        jPanelFormulario.add(jLDProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jTFFecha.setBackground(new java.awt.Color(220, 220, 220));
        jTFFecha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFFecha.setForeground(new java.awt.Color(102, 102, 102));
        jTFFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelFormulario.add(jTFFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 180, 30));

        jAstUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jAstUsuario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstUsuario.setForeground(new java.awt.Color(255, 102, 51));
        jAstUsuario.setText("*");
        jPanelFormulario.add(jAstUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        jTFCodigo.setBackground(new java.awt.Color(220, 220, 220));
        jTFCodigo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFCodigo.setForeground(new java.awt.Color(102, 102, 102));
        jTFCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelFormulario.add(jTFCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 150, 30));

        getContentPane().add(jPanelFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 850, 400));

        jPanelLateralI.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLateralI.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLateralI.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanelLateralI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelLateralI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 100, 510));

        jPanelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelWindowTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelWindowTitle.setForeground(new java.awt.Color(255, 102, 51));
        jLabelWindowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWindowTitle.setText("FORMULARIO REPORTE AVERIA PRODUCTO");
        jPanelTitulo.add(jLabelWindowTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 670, 50));

        jLabelMiniUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconUserMini.png"))); // NOI18N
        jPanelTitulo.add(jLabelMiniUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        jLabelUserName.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUserName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Administrador");
        jPanelTitulo.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 90, -1));

        getContentPane().add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 100));

        jPanelLateralD.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLateralD.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLateralD.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanelLateralD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconInformation.png"))); // NOI18N
        jBInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBInformacionMouseClicked(evt);
            }
        });
        jPanelLateralD.add(jBInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        getContentPane().add(jPanelLateralD, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 100, 510));

        jPanelBotones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBSalir.setBackground(new java.awt.Color(204, 204, 255));
        jBSalir.setText("SALIR");
        jBSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jBSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSalirMouseClicked(evt);
            }
        });
        jPanelBotones.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 120, 40));

        jBGuardar.setBackground(new java.awt.Color(204, 204, 255));
        jBGuardar.setText("GUARDAR");
        jBGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jBGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBGuardarMouseClicked(evt);
            }
        });
        jPanelBotones.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, 40));

        getContentPane().add(jPanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 850, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalirMouseClicked
        controlMenu.irModuloGInventario(user);
        this.setVisible(false);
    }//GEN-LAST:event_jBSalirMouseClicked

    private void jBGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGuardarMouseClicked
       
       report = new Reporte();
       tomarInfoReporte();
       controlReport.procesarRegistroReporte(report);
       borrarInfoCampos();
    }//GEN-LAST:event_jBGuardarMouseClicked
    
    private void tomarInfoReporte()
    {
        report.setCodigo(jTFCodigo.getText());
        report.setFecha(jTFFecha.getText());
        report.setTipo(jTFTipo.getText());
        report.setEstado("NoRevisado");
        report.setCodUsuario(jTFAlmacenista.getText());
        report.setCodProducto(jTFCProduct.getText());
        report.setNomInteresado(jTFProveedor.getText());
        report.setComentario(jTAComentario.getText());
    }
    
    private void borrarInfoCampos()
    {
        jTFCodigo.setText("");
        jTFFecha.setText("");
        jTFAlmacenista.setText("");
        jTFProveedor.setText("");
        jTFCProduct.setText("");
        jTFDescripProducto.setText("");
        jTAComentario.setText("Explique brevemente el motivo del cambio...");
    }
    
    
    private void jBAddProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAddProductoMouseClicked
        
       ControladorInventario controlInv = new ControladorInventario();
       
       Producto producto = controlInv.procesarVistaProducto
                                                        (jTFCProduct.getText());
       
       if(controlInv.getDatoEncontrado())
       { 
            jTFDescripProducto.setText(producto.getDescripcion());
            jTFProveedor.setText(producto.getProveedor());
            
       }else
       {
 
            jTFCProduct.setText("");
       }
    }//GEN-LAST:event_jBAddProductoMouseClicked

    private void jTFCProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFCProductMouseClicked
        jTFCProduct.setText("");
    }//GEN-LAST:event_jTFCProductMouseClicked

    private void jTAComentarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTAComentarioMouseClicked
        jTAComentario.setText("");
    }//GEN-LAST:event_jTAComentarioMouseClicked

    private void jBInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBInformacionMouseClicked
        jTFCodigo.setText("R-005");
        jTFFecha.setText("2019-10-01");
        jTFAlmacenista.setText("A-003");
        jTFCProduct.setText("DSC-001");
        jTAComentario.setText("¡El empaque del producto esta deteriorado!");
    }//GEN-LAST:event_jBInformacionMouseClicked

    private final Usuario user;
    private Reporte report;
    private final ControladorReporte controlReport;
    private final ControladorMenu controlMenu;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAstCodigo;
    private javax.swing.JLabel jAstComentario;
    private javax.swing.JLabel jAstFecha;
    private javax.swing.JLabel jAstTipo;
    private javax.swing.JLabel jAstUsuario;
    private javax.swing.JLabel jBAddProducto;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JLabel jBInformacion;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLComentarios;
    private javax.swing.JLabel jLDProducto;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLProducto;
    private javax.swing.JLabel jLProveedor;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabelMiniUser1;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelWindowTitle;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JPanel jPanelLateralD;
    private javax.swing.JPanel jPanelLateralI;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JSeparator jSDProducto;
    private javax.swing.JSeparator jSProveedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAComentario;
    private javax.swing.JTextField jTFAlmacenista;
    private javax.swing.JTextField jTFCProduct;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JLabel jTFDescripProducto;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JLabel jTFProveedor;
    private javax.swing.JTextField jTFTipo;
    // End of variables declaration//GEN-END:variables
}
