/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGestionReporte;

import conexionBDInventario.ConexionBDInventario;
import modeloGestionInventario.Producto;
import conexionBDGestionReporte.ConexionBDReporte;
import controladorGestionInventario.ControladorInventario;
import controladorGestionReporte.ControladorReporte;
import controladorGestionUsuario.ControladorMenu;
import modeloGestionReporte.Reporte;
import modeloGestionUsuario.Usuario;
import vistaMensEmerg.VentanaMActualizacionExit;
import vistaMensEmerg.VentanaMActualizacionNExit;

/**
 *
 * @author Aidis
 */
public class VentanaVerReporte extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public VentanaVerReporte(Usuario user, Reporte report) {
        initComponents();
        //Centra la ventana
        this.setLocationRelativeTo(null);
        this.user = user;
        jLabelUserName.setText(user.getNombreUsuario()); 
        this.report = report;
        visualizarInformacionReporte();
        controlReport = new ControladorReporte();
        controlMenu = new ControladorMenu();
        
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLateralI = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelWindowTitle = new javax.swing.JLabel();
        jLabelMiniUser1 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jPanelLateralD = new javax.swing.JPanel();
        jPanelBotones = new javax.swing.JPanel();
        jBDenegar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBAutorizar = new javax.swing.JButton();
        jPanelFormulario = new javax.swing.JPanel();
        jLProducto = new javax.swing.JLabel();
        jTFInteresado = new javax.swing.JLabel();
        jSInteresado = new javax.swing.JSeparator();
        jTFProducto = new javax.swing.JLabel();
        jSProducto = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAComentario = new javax.swing.JTextArea();
        jLComentarios = new javax.swing.JLabel();
        jTFTipo = new javax.swing.JLabel();
        jSTipo = new javax.swing.JSeparator();
        jLTipo = new javax.swing.JLabel();
        jLCodigo = new javax.swing.JLabel();
        jLInteresado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLateralI.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLateralI.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLateralI.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanelLateralI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelLateralI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, 490));

        jPanelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelWindowTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelWindowTitle.setForeground(new java.awt.Color(255, 102, 51));
        jLabelWindowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWindowTitle.setText("VER REPORTE");
        jPanelTitulo.add(jLabelWindowTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 280, 40));

        jLabelMiniUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconUserMini.png"))); // NOI18N
        jPanelTitulo.add(jLabelMiniUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, 40));

        jLabelUserName.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUserName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Administrador");
        jPanelTitulo.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, 90, -1));

        getContentPane().add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 90));

        jPanelLateralD.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLateralD.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLateralD.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanelLateralD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelLateralD, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, 100, 490));

        jPanelBotones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBDenegar.setBackground(new java.awt.Color(204, 204, 255));
        jBDenegar.setText("DENEGAR");
        jBDenegar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jBDenegar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBDenegar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBDenegarMouseClicked(evt);
            }
        });
        jPanelBotones.add(jBDenegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 120, 40));

        jBSalir.setBackground(new java.awt.Color(204, 204, 255));
        jBSalir.setText("SALIR");
        jBSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jBSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSalirMouseClicked(evt);
            }
        });
        jPanelBotones.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 120, 40));

        jBAutorizar.setBackground(new java.awt.Color(204, 204, 255));
        jBAutorizar.setText("AUTORIZAR");
        jBAutorizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jBAutorizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAutorizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAutorizarMouseClicked(evt);
            }
        });
        jPanelBotones.add(jBAutorizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 40));

        getContentPane().add(jPanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 850, 120));

        jPanelFormulario.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFormulario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanelFormulario.setForeground(new java.awt.Color(255, 255, 255));
        jPanelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLProducto.setBackground(new java.awt.Color(0, 0, 0));
        jLProducto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLProducto.setText("PRODUCTO");
        jPanelFormulario.add(jLProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jTFInteresado.setBackground(new java.awt.Color(255, 255, 255));
        jTFInteresado.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFInteresado.setForeground(new java.awt.Color(102, 102, 102));
        jTFInteresado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFInteresado.setOpaque(true);
        jPanelFormulario.add(jTFInteresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 450, 30));

        jSInteresado.setForeground(new java.awt.Color(255, 102, 51));
        jPanelFormulario.add(jSInteresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 450, 20));

        jTFProducto.setBackground(new java.awt.Color(255, 255, 255));
        jTFProducto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFProducto.setForeground(new java.awt.Color(102, 102, 102));
        jTFProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFProducto.setOpaque(true);
        jPanelFormulario.add(jTFProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 450, 30));

        jSProducto.setForeground(new java.awt.Color(255, 102, 51));
        jPanelFormulario.add(jSProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 450, 10));

        jTAComentario.setBackground(new java.awt.Color(220, 220, 220));
        jTAComentario.setColumns(20);
        jTAComentario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTAComentario.setForeground(new java.awt.Color(102, 102, 102));
        jTAComentario.setRows(5);
        jTAComentario.setText("Explique brevemente el motivo del cambio...\n\nADMINISTRADOR:\nSugiero que se lleve a cabo ....");
        jTAComentario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jScrollPane1.setViewportView(jTAComentario);

        jPanelFormulario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 460, 120));

        jLComentarios.setBackground(new java.awt.Color(0, 0, 0));
        jLComentarios.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLComentarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLComentarios.setText("COMENTARIOS");
        jPanelFormulario.add(jLComentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 120, -1));

        jTFTipo.setBackground(new java.awt.Color(255, 255, 255));
        jTFTipo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFTipo.setForeground(new java.awt.Color(102, 102, 102));
        jTFTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFTipo.setOpaque(true);
        jPanelFormulario.add(jTFTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 150, 30));

        jSTipo.setForeground(new java.awt.Color(255, 102, 51));
        jPanelFormulario.add(jSTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 150, 20));

        jLTipo.setBackground(new java.awt.Color(0, 0, 0));
        jLTipo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTipo.setText("TIPO");
        jPanelFormulario.add(jLTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLCodigo.setBackground(new java.awt.Color(255, 255, 255));
        jLCodigo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCodigo.setText("R-001");
        jLCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jLCodigo.setOpaque(true);
        jPanelFormulario.add(jLCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        jLInteresado.setBackground(new java.awt.Color(0, 0, 0));
        jLInteresado.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLInteresado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLInteresado.setText("INTERESADO");
        jPanelFormulario.add(jLInteresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        getContentPane().add(jPanelFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 850, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visualizarInformacionReporte()
    {
        jLCodigo.setText(report.getCodigo());
        jTFTipo.setText(report.getTipo());
        jTFInteresado.setText(report.getNomInteresado());
        ControladorInventario controlInv = new ControladorInventario();
        Producto miProducto = controlInv.procesarVistaProducto(report.getCodProducto());
        jTFProducto.setText(miProducto.getDescripcion());
        jTAComentario.setText(report.getComentario());
    }
    
    
    private void jBSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalirMouseClicked
        controlMenu.irModuloGReporte(user);
        this.setVisible(false);
    }//GEN-LAST:event_jBSalirMouseClicked

    private void jBDenegarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDenegarMouseClicked
          
        controlReport.procesarEdicionEstadoReporte("estado", "Denegado", 
                                                          jLCodigo.getText());
         
    }//GEN-LAST:event_jBDenegarMouseClicked

    private void jBAutorizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAutorizarMouseClicked
        
        controlReport.procesarEdicionEstadoReporte("estado", "Autorizado", 
                                                           jLCodigo.getText());
       
    }//GEN-LAST:event_jBAutorizarMouseClicked
    
    private final Usuario user;
    private final Reporte report;
    private final ControladorReporte controlReport;
    private final ControladorMenu controlMenu;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAutorizar;
    private javax.swing.JButton jBDenegar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLComentarios;
    private javax.swing.JLabel jLInteresado;
    private javax.swing.JLabel jLProducto;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLabelMiniUser1;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelWindowTitle;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JPanel jPanelLateralD;
    private javax.swing.JPanel jPanelLateralI;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JSeparator jSInteresado;
    private javax.swing.JSeparator jSProducto;
    private javax.swing.JSeparator jSTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAComentario;
    private javax.swing.JLabel jTFInteresado;
    private javax.swing.JLabel jTFProducto;
    private javax.swing.JLabel jTFTipo;
    // End of variables declaration//GEN-END:variables
}
