/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontendGestionInventario;

import backendGestionInventario.*;
import modeloGestionUsuario.Usuario;
import frontendMensEmerg.VentanaMensajeError;

/**
 *
 * @author Aidis
 */
public class VentanaVerProducto extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public VentanaVerProducto(Usuario user) {
        initComponents();
        //Centra la ventana
        this.setLocationRelativeTo(null);
        this.user = new Usuario();
        this.user = user;
        jLabelUserName.setText(user.getNombreUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneMenuLateral = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelWindowTitle = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelMiniUser1 = new javax.swing.JLabel();
        jPaneMenuLateral1 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jPanelBotones = new javax.swing.JPanel();
        jLabelUserName1 = new javax.swing.JLabel();
        jLabelImageExit1 = new javax.swing.JLabel();
        jLabelMiniUser2 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jPanelTitulo3 = new javax.swing.JPanel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jLabelNombre3 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelCC = new javax.swing.JLabel();
        jLabelBornDay = new javax.swing.JLabel();
        jLabelAsterisco5 = new javax.swing.JLabel();
        jLabelCargo = new javax.swing.JLabel();
        jLabelNombre5 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JLabel();
        jSeparatorUsuario = new javax.swing.JSeparator();
        jTextFieldProveedor = new javax.swing.JLabel();
        jSeparatorUsuario1 = new javax.swing.JSeparator();
        jTextFieldFecha = new javax.swing.JLabel();
        jSeparatorUsuario2 = new javax.swing.JSeparator();
        jTextFieldPVenta = new javax.swing.JLabel();
        jSeparatorUsuario3 = new javax.swing.JSeparator();
        jLabelCodigo1 = new javax.swing.JLabel();
        jSeparatorUsuario4 = new javax.swing.JSeparator();
        jTextFieldTipo = new javax.swing.JLabel();
        jSeparatorUsuario5 = new javax.swing.JSeparator();
        jLabelCodigo2 = new javax.swing.JLabel();
        jLabelBornDay1 = new javax.swing.JLabel();
        jTextFieldPCompra = new javax.swing.JLabel();
        jSeparatorUsuario6 = new javax.swing.JSeparator();
        jTextFieldDescrip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPaneMenuLateral.setBackground(new java.awt.Color(255, 255, 255));
        jPaneMenuLateral.setForeground(new java.awt.Color(255, 255, 255));
        jPaneMenuLateral.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPaneMenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 253, 1, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 257, 1, 22));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setForeground(new java.awt.Color(255, 102, 51));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 60, 290, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 102, 51));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 290, 10));

        jPaneMenuLateral.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 10));

        getContentPane().add(jPaneMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 100, 460));

        jPanelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelWindowTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelWindowTitle.setForeground(new java.awt.Color(255, 102, 51));
        jLabelWindowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWindowTitle.setText("VER PRODUCTO");
        jPanelTitulo.add(jLabelWindowTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 280, 40));

        jLabelUserName.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUserName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Administrador");
        jPanelTitulo.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, -1, -1));

        jLabelMiniUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconUserMini.png"))); // NOI18N
        jPanelTitulo.add(jLabelMiniUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, 40));

        getContentPane().add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        jPaneMenuLateral1.setBackground(new java.awt.Color(255, 255, 255));
        jPaneMenuLateral1.setForeground(new java.awt.Color(255, 255, 255));
        jPaneMenuLateral1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPaneMenuLateral1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 253, 1, 10));

        jSeparator7.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 257, 1, 22));

        getContentPane().add(jPaneMenuLateral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 100, 460));

        jPanelBotones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUserName1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUserName1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelUserName1.setText("Administrador");
        jPanelBotones.add(jLabelUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, -1, -1));

        jLabelImageExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconExit.png"))); // NOI18N
        jLabelImageExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImageExit1MouseClicked(evt);
            }
        });
        jPanelBotones.add(jLabelImageExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, -1));

        jLabelMiniUser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconUserMini.png"))); // NOI18N
        jPanelBotones.add(jLabelMiniUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 255));
        jButtonSalir.setText("SALIR");
        jButtonSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseClicked(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 120, 40));

        getContentPane().add(jPanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 850, 120));

        jPanelTitulo3.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTitulo3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldBuscar.setBackground(new java.awt.Color(220, 220, 220));
        jTextFieldBuscar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldBuscar.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldBuscar.setText("Buscar");
        jTextFieldBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jTextFieldBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBuscarFocusGained(evt);
            }
        });
        jTextFieldBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBuscarMouseClicked(evt);
            }
        });
        jPanelTitulo3.add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 520, 30));

        jLabelNombre3.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNombre3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelNombre3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombre3.setText("CODIGO");
        jPanelTitulo3.add(jLabelNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 30));

        jButtonBuscar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBuscar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconSearch.png"))); // NOI18N
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseClicked(evt);
            }
        });
        jPanelTitulo3.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, 30));

        getContentPane().add(jPanelTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1050, 80));

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCodigo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCodigo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCodigo.setText("FECHA VENCIMIENTO");
        jPanelMenu.add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jLabelCC.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCC.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCC.setText("DESCRIPCIÓN");
        jPanelMenu.add(jLabelCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabelBornDay.setBackground(new java.awt.Color(0, 0, 0));
        jLabelBornDay.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelBornDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBornDay.setText("PRECIO VENTA");
        jPanelMenu.add(jLabelBornDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabelAsterisco5.setBackground(new java.awt.Color(0, 0, 0));
        jLabelAsterisco5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAsterisco5.setForeground(new java.awt.Color(255, 102, 51));
        jLabelAsterisco5.setText("*");
        jPanelMenu.add(jLabelAsterisco5, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 160, 0, -1));

        jLabelCargo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCargo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelCargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCargo.setText("CANTIDAD");
        jPanelMenu.add(jLabelCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        jLabelNombre5.setBackground(new java.awt.Color(220, 220, 220));
        jLabelNombre5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelNombre5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombre5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconSoup.png"))); // NOI18N
        jLabelNombre5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jLabelNombre5.setOpaque(true);
        jPanelMenu.add(jLabelNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 250, 220));

        jTextFieldCantidad.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCantidad.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldCantidad.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTextFieldCantidad.setOpaque(true);
        jPanelMenu.add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 130, 20));

        jSeparatorUsuario.setForeground(new java.awt.Color(255, 102, 51));
        jPanelMenu.add(jSeparatorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 130, 20));

        jTextFieldProveedor.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldProveedor.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldProveedor.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTextFieldProveedor.setOpaque(true);
        jPanelMenu.add(jTextFieldProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 370, 30));

        jSeparatorUsuario1.setForeground(new java.awt.Color(255, 102, 51));
        jPanelMenu.add(jSeparatorUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 370, 10));

        jTextFieldFecha.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFecha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldFecha.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTextFieldFecha.setOpaque(true);
        jPanelMenu.add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 130, 30));

        jSeparatorUsuario2.setForeground(new java.awt.Color(255, 102, 51));
        jPanelMenu.add(jSeparatorUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 130, 10));

        jTextFieldPVenta.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPVenta.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldPVenta.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTextFieldPVenta.setOpaque(true);
        jPanelMenu.add(jTextFieldPVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 340, 30));

        jSeparatorUsuario3.setForeground(new java.awt.Color(255, 102, 51));
        jPanelMenu.add(jSeparatorUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 340, 20));

        jLabelCodigo1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCodigo1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelCodigo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCodigo1.setText("PROVEEDOR");
        jPanelMenu.add(jLabelCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jSeparatorUsuario4.setForeground(new java.awt.Color(255, 102, 51));
        jPanelMenu.add(jSeparatorUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 370, 10));

        jTextFieldTipo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTipo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldTipo.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTextFieldTipo.setOpaque(true);
        jPanelMenu.add(jTextFieldTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 120, 30));

        jSeparatorUsuario5.setForeground(new java.awt.Color(255, 102, 51));
        jPanelMenu.add(jSeparatorUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 120, 10));

        jLabelCodigo2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCodigo2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelCodigo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCodigo2.setText("TIPO");
        jPanelMenu.add(jLabelCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabelBornDay1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelBornDay1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelBornDay1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBornDay1.setText("PRECIO COMPRA");
        jPanelMenu.add(jLabelBornDay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jTextFieldPCompra.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPCompra.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldPCompra.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTextFieldPCompra.setOpaque(true);
        jPanelMenu.add(jTextFieldPCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 340, 30));

        jSeparatorUsuario6.setForeground(new java.awt.Color(255, 102, 51));
        jPanelMenu.add(jSeparatorUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 340, 20));

        jTextFieldDescrip.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDescrip.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldDescrip.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldDescrip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTextFieldDescrip.setOpaque(true);
        jPanelMenu.add(jTextFieldDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 380, 30));

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 850, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseClicked
                  //Creación objeto ventana Usuarios
        VentanaPrincipalInventario ventanaI = new VentanaPrincipalInventario(user);
        ventanaI.setVisible(true);//mostrar ventana usuarios
        this.setVisible(false);//Ocultar ventana en la que me encuentro
    }//GEN-LAST:event_jButtonSalirMouseClicked

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jLabelImageExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImageExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelImageExit1MouseClicked

    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseClicked
        ConexionBDInventario conexionBD = new ConexionBDInventario();
        
       Producto miProducto = conexionBD.consultarProducto(jTextFieldBuscar.getText());
       if(conexionBD.getDatoEncontrado())
       { 
            jTextFieldDescrip.setText(miProducto.getDescripcion());
            jTextFieldProveedor.setText(miProducto.getProveedor());
            jTextFieldTipo.setText(miProducto.getTipo());
            jTextFieldFecha.setText(miProducto.getFechaV());
            jTextFieldPCompra.setText(miProducto.getPrecioCompra());
            jTextFieldPVenta.setText(miProducto.getPrecioVenta());
            jTextFieldCantidad.setText(miProducto.getCantidad());
            
       }else
       {
           VentanaMensajeError mensajeError = new VentanaMensajeError();
           mensajeError.setVisible(true);
            jTextFieldDescrip.setText("");
            jTextFieldProveedor.setText("");
            jTextFieldTipo.setText("");
            jTextFieldFecha.setText("");
            jTextFieldPCompra.setText("");
            jTextFieldPVenta.setText("");
            jTextFieldCantidad.setText("");
       }
    }//GEN-LAST:event_jButtonBuscarMouseClicked

    private void jTextFieldBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBuscarFocusGained
        jTextFieldBuscar.setText("");
    }//GEN-LAST:event_jTextFieldBuscarFocusGained

    private void jTextFieldBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBuscarMouseClicked
            jTextFieldBuscar.setText("");
            jTextFieldDescrip.setText("");
            jTextFieldProveedor.setText("");
            jTextFieldTipo.setText("");
            jTextFieldFecha.setText("");
            jTextFieldPCompra.setText("");
            jTextFieldPVenta.setText("");
            jTextFieldCantidad.setText("");
    }//GEN-LAST:event_jTextFieldBuscarMouseClicked
    private Usuario user;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jButtonBuscar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelAsterisco5;
    private javax.swing.JLabel jLabelBornDay;
    private javax.swing.JLabel jLabelBornDay1;
    private javax.swing.JLabel jLabelCC;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCodigo1;
    private javax.swing.JLabel jLabelCodigo2;
    private javax.swing.JLabel jLabelImageExit1;
    private javax.swing.JLabel jLabelMiniUser1;
    private javax.swing.JLabel jLabelMiniUser2;
    private javax.swing.JLabel jLabelNombre3;
    private javax.swing.JLabel jLabelNombre5;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelUserName1;
    private javax.swing.JLabel jLabelWindowTitle;
    private javax.swing.JPanel jPaneMenuLateral;
    private javax.swing.JPanel jPaneMenuLateral1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPanel jPanelTitulo3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparatorUsuario;
    private javax.swing.JSeparator jSeparatorUsuario1;
    private javax.swing.JSeparator jSeparatorUsuario2;
    private javax.swing.JSeparator jSeparatorUsuario3;
    private javax.swing.JSeparator jSeparatorUsuario4;
    private javax.swing.JSeparator jSeparatorUsuario5;
    private javax.swing.JSeparator jSeparatorUsuario6;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JLabel jTextFieldCantidad;
    private javax.swing.JLabel jTextFieldDescrip;
    private javax.swing.JLabel jTextFieldFecha;
    private javax.swing.JLabel jTextFieldPCompra;
    private javax.swing.JLabel jTextFieldPVenta;
    private javax.swing.JLabel jTextFieldProveedor;
    private javax.swing.JLabel jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
