/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaGestionCliente;

import modeloGestionCliente.Cliente;
import controladorGestionCliente.ControladorCliente;
import controladorGestionUsuario.ControladorMenu;
import modeloGestionUsuario.Usuario;

/**
 *
 * @author Aidis
 */
public class VentanaEdicionCliente extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public VentanaEdicionCliente(Usuario user ) {
        initComponents();
        //Centra la ventana
        this.setLocationRelativeTo(null);
        this.user = user;
        count =0;
        controlClient = new ControladorCliente();
        controlMenu = new ControladorMenu();
        jLabelUserName.setText(user.getNombreUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLateralI = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelWindowTitle = new javax.swing.JLabel();
        jLabelMiniUser1 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jPanelLateralD = new javax.swing.JPanel();
        jPanelBotones = new javax.swing.JPanel();
        jBSalir = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jPanelBusqueda = new javax.swing.JPanel();
        jTFBuscar = new javax.swing.JTextField();
        jLCC = new javax.swing.JLabel();
        jBBuscar = new javax.swing.JLabel();
        jPanelFormulario = new javax.swing.JPanel();
        jLTelefono = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jAstNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFTelefono = new javax.swing.JTextField();
        jLFecha = new javax.swing.JLabel();
        jAstFecha = new javax.swing.JLabel();
        jAstTelefono = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jLDireccion = new javax.swing.JLabel();
        jAstDireccion = new javax.swing.JLabel();
        jTFFecha = new javax.swing.JTextField();
        jLEmail = new javax.swing.JLabel();
        jAstEmail = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLateralI.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLateralI.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLateralI.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanelLateralI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelLateralI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 100, 460));

        jPanelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelWindowTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelWindowTitle.setForeground(new java.awt.Color(255, 102, 51));
        jLabelWindowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWindowTitle.setText("FORMULARIO EDICIÓN CLIENTE");
        jPanelTitulo.add(jLabelWindowTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 510, 40));

        jLabelMiniUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconUserMini.png"))); // NOI18N
        jPanelTitulo.add(jLabelMiniUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, 40));

        jLabelUserName.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUserName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Administrador");
        jPanelTitulo.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, 90, -1));

        getContentPane().add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        jPanelLateralD.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLateralD.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLateralD.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanelLateralD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelLateralD, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 150, 100, 430));

        jPanelBotones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBSalir.setBackground(new java.awt.Color(204, 204, 255));
        jBSalir.setText("SALIR");
        jBSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jBSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSalirMouseClicked(evt);
            }
        });
        jPanelBotones.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 120, 40));

        jBGuardar.setBackground(new java.awt.Color(204, 204, 255));
        jBGuardar.setText("GUARDAR");
        jBGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jBGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBGuardarMouseClicked(evt);
            }
        });
        jPanelBotones.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 40));

        getContentPane().add(jPanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 850, 100));

        jPanelBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFBuscar.setBackground(new java.awt.Color(220, 220, 220));
        jTFBuscar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFBuscar.setForeground(new java.awt.Color(102, 102, 102));
        jTFBuscar.setText("Buscar");
        jTFBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jTFBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFBuscarMouseClicked(evt);
            }
        });
        jPanelBusqueda.add(jTFBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 320, 30));

        jLCC.setBackground(new java.awt.Color(0, 0, 0));
        jLCC.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCC.setText("C.C");
        jPanelBusqueda.add(jLCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, 30));

        jBBuscar.setBackground(new java.awt.Color(0, 0, 0));
        jBBuscar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconSearch.png"))); // NOI18N
        jBBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBuscarMouseClicked(evt);
            }
        });
        jPanelBusqueda.add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, 30));

        getContentPane().add(jPanelBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1050, 80));

        jPanelFormulario.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFormulario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanelFormulario.setForeground(new java.awt.Color(255, 255, 255));
        jPanelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTelefono.setBackground(new java.awt.Color(0, 0, 0));
        jLTelefono.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLTelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTelefono.setText("TELEFONO");
        jPanelFormulario.add(jLTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        jLNombre.setBackground(new java.awt.Color(0, 0, 0));
        jLNombre.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNombre.setText("NOMBRE");
        jPanelFormulario.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jAstNombre.setBackground(new java.awt.Color(0, 0, 0));
        jAstNombre.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstNombre.setForeground(new java.awt.Color(255, 102, 51));
        jAstNombre.setText("*");
        jPanelFormulario.add(jAstNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jTFNombre.setBackground(new java.awt.Color(220, 220, 220));
        jTFNombre.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFNombre.setForeground(new java.awt.Color(102, 102, 102));
        jTFNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelFormulario.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 590, 30));

        jTFTelefono.setBackground(new java.awt.Color(220, 220, 220));
        jTFTelefono.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFTelefono.setForeground(new java.awt.Color(102, 102, 102));
        jTFTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelFormulario.add(jTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 180, 30));

        jLFecha.setBackground(new java.awt.Color(0, 0, 0));
        jLFecha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFecha.setText("FECHA REGISTRO");
        jPanelFormulario.add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        jAstFecha.setBackground(new java.awt.Color(0, 0, 0));
        jAstFecha.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstFecha.setForeground(new java.awt.Color(255, 102, 51));
        jAstFecha.setText("*");
        jPanelFormulario.add(jAstFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        jAstTelefono.setBackground(new java.awt.Color(0, 0, 0));
        jAstTelefono.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstTelefono.setForeground(new java.awt.Color(255, 102, 51));
        jAstTelefono.setText("*");
        jPanelFormulario.add(jAstTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        jTFDireccion.setBackground(new java.awt.Color(220, 220, 220));
        jTFDireccion.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFDireccion.setForeground(new java.awt.Color(102, 102, 102));
        jTFDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelFormulario.add(jTFDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 220, 30));

        jLDireccion.setBackground(new java.awt.Color(0, 0, 0));
        jLDireccion.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLDireccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDireccion.setText("DIRECCIÓN");
        jPanelFormulario.add(jLDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 90, -1));

        jAstDireccion.setBackground(new java.awt.Color(0, 0, 0));
        jAstDireccion.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstDireccion.setForeground(new java.awt.Color(255, 102, 51));
        jAstDireccion.setText("*");
        jPanelFormulario.add(jAstDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 10, -1));

        jTFFecha.setBackground(new java.awt.Color(220, 220, 220));
        jTFFecha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFFecha.setForeground(new java.awt.Color(102, 102, 102));
        jTFFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelFormulario.add(jTFFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 180, 30));

        jLEmail.setBackground(new java.awt.Color(0, 0, 0));
        jLEmail.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEmail.setText("EMAIL");
        jPanelFormulario.add(jLEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jAstEmail.setBackground(new java.awt.Color(0, 0, 0));
        jAstEmail.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jAstEmail.setForeground(new java.awt.Color(255, 102, 51));
        jAstEmail.setText("*");
        jPanelFormulario.add(jAstEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jTFEmail.setBackground(new java.awt.Color(220, 220, 220));
        jTFEmail.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTFEmail.setForeground(new java.awt.Color(102, 102, 102));
        jTFEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelFormulario.add(jTFEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 220, 30));

        getContentPane().add(jPanelFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 850, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalirMouseClicked
        controlMenu.irModuloGCliente(user);
        this.setVisible(false);
    }//GEN-LAST:event_jBSalirMouseClicked
    
    private void editarCampo(String campo, String valor, String codigo)
    {
       count++;
       controlClient.procesarEdicionCliente(campo, valor, codigo, count); 
    }
    
    private void jBGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGuardarMouseClicked
        count =0;
 
        String docId = jTFBuscar.getText();

        editarCampo("nombre",jTFNombre.getText(), docId);
                
        editarCampo("telefono",jTFTelefono.getText(), docId);

        editarCampo("direccion",jTFDireccion.getText(), docId);

        editarCampo("fecharegistro",jTFFecha.getText(),docId);
        
        editarCampo("email",jTFEmail.getText(),docId);

    }//GEN-LAST:event_jBGuardarMouseClicked
    
    private void mostrarInfoUsuario()
    {
        jTFNombre.setText(client.getNombre());
        jTFDireccion.setText(client.getDireccion());
        jTFTelefono.setText(client.getTelefono());
        jTFFecha.setText(client.getFechaRegistro());
        jTFEmail.setText(client.getEmail());
    }
    
    private void borrarInfoCampos()
    {
        jTFBuscar.setText("Buscar");
        jTFNombre.setText("");
        jTFDireccion.setText("");
        jTFTelefono.setText("");
        jTFFecha.setText("");
        jTFEmail.setText("");
        
    }
    
    private void jBBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBuscarMouseClicked
       
       client = controlClient.procesarVistaCliente(jTFBuscar.getText());
       
       if(controlClient.getEncontrado())
       { 
           mostrarInfoUsuario();

       }else
       {
           borrarInfoCampos();
           
       }
    }//GEN-LAST:event_jBBuscarMouseClicked

    private void jTFBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFBuscarMouseClicked
        jTFBuscar.setText("");
    }//GEN-LAST:event_jTFBuscarMouseClicked
    
    private Cliente client;
    private int count;
    private final ControladorCliente controlClient;
    private final ControladorMenu controlMenu;
    private final Usuario user;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAstDireccion;
    private javax.swing.JLabel jAstEmail;
    private javax.swing.JLabel jAstFecha;
    private javax.swing.JLabel jAstNombre;
    private javax.swing.JLabel jAstTelefono;
    private javax.swing.JLabel jBBuscar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLCC;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JLabel jLabelMiniUser1;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelWindowTitle;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelBusqueda;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JPanel jPanelLateralD;
    private javax.swing.JPanel jPanelLateralI;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JTextField jTFBuscar;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFTelefono;
    // End of variables declaration//GEN-END:variables
}
