/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontendGestionCliente;

import backendGestionCliente.Cliente;
import backendGestionCliente.ConexionBDCliente;
import modeloGestionUsuario.Usuario;
import frontendMensEmerg.*;

/**
 *
 * @author Aidis
 */
public class VentanaEdicionCliente extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public VentanaEdicionCliente(Usuario user ) {
        initComponents();
        //Centra la ventana
        this.setLocationRelativeTo(null);
        this.user = new Usuario();
        this.user = user;
        jLabelUserName.setText(user.getNombreUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneMenuLateral = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelWindowTitle = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelMiniUser1 = new javax.swing.JLabel();
        jPaneMenuLateral1 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jPanelBotones = new javax.swing.JPanel();
        jLabelUserName1 = new javax.swing.JLabel();
        jLabelImageExit1 = new javax.swing.JLabel();
        jLabelMiniUser2 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jPanelTitulo3 = new javax.swing.JPanel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jLabelCC = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JLabel();
        jPanelMenu1 = new javax.swing.JPanel();
        jLabelTelefono1 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelAsterisco10 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelCodigo1 = new javax.swing.JLabel();
        jLabelAsterisco11 = new javax.swing.JLabel();
        jLabelAsterisco13 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelAsterisco14 = new javax.swing.JLabel();
        jLabelAsterisco15 = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabelAsterisco16 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPaneMenuLateral.setBackground(new java.awt.Color(255, 255, 255));
        jPaneMenuLateral.setForeground(new java.awt.Color(255, 255, 255));
        jPaneMenuLateral.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPaneMenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 253, 1, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 257, 1, 22));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setForeground(new java.awt.Color(255, 102, 51));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 60, 290, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 102, 51));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 290, 10));

        jPaneMenuLateral.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 10));

        getContentPane().add(jPaneMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 100, 460));

        jPanelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelWindowTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelWindowTitle.setForeground(new java.awt.Color(255, 102, 51));
        jLabelWindowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWindowTitle.setText("FORMULARIO EDICIÓN CLIENTE");
        jPanelTitulo.add(jLabelWindowTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 510, 40));

        jLabelUserName.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUserName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Administrador");
        jPanelTitulo.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, -1, -1));

        jLabelMiniUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconUserMini.png"))); // NOI18N
        jPanelTitulo.add(jLabelMiniUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, 40));

        getContentPane().add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        jPaneMenuLateral1.setBackground(new java.awt.Color(255, 255, 255));
        jPaneMenuLateral1.setForeground(new java.awt.Color(255, 255, 255));
        jPaneMenuLateral1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPaneMenuLateral1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 253, 1, 10));

        jSeparator7.setForeground(new java.awt.Color(255, 102, 51));
        jPaneMenuLateral1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 257, 1, 22));

        getContentPane().add(jPaneMenuLateral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 100, 460));

        jPanelBotones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUserName1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUserName1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelUserName1.setText("Administrador");
        jPanelBotones.add(jLabelUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, -1, -1));

        jLabelImageExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconExit.png"))); // NOI18N
        jLabelImageExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImageExit1MouseClicked(evt);
            }
        });
        jPanelBotones.add(jLabelImageExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, -1));

        jLabelMiniUser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconUserMini.png"))); // NOI18N
        jPanelBotones.add(jLabelMiniUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 255));
        jButtonSalir.setText("SALIR");
        jButtonSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseClicked(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 120, 40));

        jButtonGuardar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonGuardar.setText("GUARDAR");
        jButtonGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));
        jButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarMouseClicked(evt);
            }
        });
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 40));

        getContentPane().add(jPanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 850, 100));

        jPanelTitulo3.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTitulo3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldBuscar.setBackground(new java.awt.Color(220, 220, 220));
        jTextFieldBuscar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldBuscar.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldBuscar.setText("Buscar");
        jTextFieldBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jTextFieldBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBuscarFocusGained(evt);
            }
        });
        jTextFieldBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBuscarMouseClicked(evt);
            }
        });
        jPanelTitulo3.add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 320, 30));

        jLabelCC.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCC.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCC.setText("C.C");
        jPanelTitulo3.add(jLabelCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, 30));

        jButtonBuscar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBuscar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconSearch.png"))); // NOI18N
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseClicked(evt);
            }
        });
        jPanelTitulo3.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, 30));

        getContentPane().add(jPanelTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1050, 80));

        jPanelMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanelMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTelefono1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTelefono1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelTelefono1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTelefono1.setText("TELEFONO");
        jPanelMenu1.add(jLabelTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        jLabelNombre.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNombre.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombre.setText("NOMBRE");
        jPanelMenu1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabelAsterisco10.setBackground(new java.awt.Color(0, 0, 0));
        jLabelAsterisco10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAsterisco10.setForeground(new java.awt.Color(255, 102, 51));
        jLabelAsterisco10.setText("*");
        jPanelMenu1.add(jLabelAsterisco10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jTextFieldNombre.setBackground(new java.awt.Color(220, 220, 220));
        jTextFieldNombre.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelMenu1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 590, 30));

        jTextFieldTelefono.setBackground(new java.awt.Color(220, 220, 220));
        jTextFieldTelefono.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldTelefono.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelMenu1.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 180, 30));

        jLabelCodigo1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCodigo1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelCodigo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCodigo1.setText("FECHA REGISTRO");
        jPanelMenu1.add(jLabelCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        jLabelAsterisco11.setBackground(new java.awt.Color(0, 0, 0));
        jLabelAsterisco11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAsterisco11.setForeground(new java.awt.Color(255, 102, 51));
        jLabelAsterisco11.setText("*");
        jPanelMenu1.add(jLabelAsterisco11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        jLabelAsterisco13.setBackground(new java.awt.Color(0, 0, 0));
        jLabelAsterisco13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAsterisco13.setForeground(new java.awt.Color(255, 102, 51));
        jLabelAsterisco13.setText("*");
        jPanelMenu1.add(jLabelAsterisco13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        jTextFieldDireccion.setBackground(new java.awt.Color(220, 220, 220));
        jTextFieldDireccion.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldDireccion.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelMenu1.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 220, 30));

        jLabelDireccion.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDireccion.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelDireccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDireccion.setText("DIRECCIÓN");
        jPanelMenu1.add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 90, -1));

        jLabelAsterisco14.setBackground(new java.awt.Color(0, 0, 0));
        jLabelAsterisco14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAsterisco14.setForeground(new java.awt.Color(255, 102, 51));
        jLabelAsterisco14.setText("*");
        jPanelMenu1.add(jLabelAsterisco14, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 160, 0, -1));

        jLabelAsterisco15.setBackground(new java.awt.Color(0, 0, 0));
        jLabelAsterisco15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAsterisco15.setForeground(new java.awt.Color(255, 102, 51));
        jLabelAsterisco15.setText("*");
        jPanelMenu1.add(jLabelAsterisco15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 10, -1));

        jTextFieldFecha.setBackground(new java.awt.Color(220, 220, 220));
        jTextFieldFecha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldFecha.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelMenu1.add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 180, 30));

        jLabelEmail.setBackground(new java.awt.Color(0, 0, 0));
        jLabelEmail.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmail.setText("EMAIL");
        jPanelMenu1.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabelAsterisco16.setBackground(new java.awt.Color(0, 0, 0));
        jLabelAsterisco16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAsterisco16.setForeground(new java.awt.Color(255, 102, 51));
        jLabelAsterisco16.setText("*");
        jPanelMenu1.add(jLabelAsterisco16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jTextFieldEmail.setBackground(new java.awt.Color(220, 220, 220));
        jTextFieldEmail.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanelMenu1.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 220, 30));

        getContentPane().add(jPanelMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 850, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseClicked
                  //Creación objeto ventana Usuarios
       VentanaPrincipalCliente ventanaC = new VentanaPrincipalCliente(user);
        ventanaC.setVisible(true);//mostrar ventana usuarios
        this.setVisible(false);//Ocultar ventana en la que me encuentro
    }//GEN-LAST:event_jButtonSalirMouseClicked

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jLabelImageExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImageExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelImageExit1MouseClicked

    private void jButtonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarMouseClicked

         boolean comp = true;
        ConexionBDCliente conexionBD = new ConexionBDCliente();
        
        String docId = jTextFieldBuscar.getText();
                
        String nombre =jTextFieldNombre.getText();
        conexionBD.actualizarCliente("nombre", nombre, docId);
        comp= comp && conexionBD.getDatoEncontrado();
        
        String tel= jTextFieldTelefono.getText();
        conexionBD.actualizarCliente("telefono",tel, docId);
        comp= comp && conexionBD.getDatoEncontrado();
        
        String direccion= jTextFieldDireccion.getText();
        conexionBD.actualizarCliente("direccion",direccion, docId);
        comp= comp && conexionBD.getDatoEncontrado();
        
        String fecha= jTextFieldFecha.getText();
        conexionBD.actualizarCliente("fecharegistro",fecha,docId);
        comp= comp && conexionBD.getDatoEncontrado();
        

        String email = jTextFieldEmail.getText();
        conexionBD.actualizarCliente("email",email,docId);
        comp= comp && conexionBD.getDatoEncontrado();

        compActualizacion(comp);

    }//GEN-LAST:event_jButtonGuardarMouseClicked
    private void compActualizacion(boolean comp)
    {
        if(comp)
        {
            VentanaMActualizacionExit  vMAE= new VentanaMActualizacionExit();
            vMAE.setVisible(true);
        }else
        {
            VentanaMActualizacionNExit  vMANE= new VentanaMActualizacionNExit();
            vMANE.setVisible(true);
        }
    }
    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombre1ActionPerformed

    private void jTextFieldBornDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBornDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBornDayActionPerformed

    private void jTextFieldCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCCActionPerformed

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jTextFieldCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCargoActionPerformed

    private void jTextFieldBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBuscarFocusGained
        
    }//GEN-LAST:event_jTextFieldBuscarFocusGained

    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseClicked
        ConexionBDCliente conexionBD = new ConexionBDCliente();
        
       Cliente miCliente= conexionBD.consultarCliente(jTextFieldBuscar.getText());
       if(conexionBD.getDatoEncontrado())
       { 
            jTextFieldNombre.setText(miCliente.getNombre());
            jTextFieldDireccion.setText(miCliente.getDireccion());
            jTextFieldTelefono.setText(miCliente.getTelefono());
            jTextFieldFecha.setText(miCliente.getFechaRegistro());
            jTextFieldEmail.setText(miCliente.getEmail());
       }else
       {
           VentanaMensajeError mensajeError = new VentanaMensajeError();
           mensajeError.setVisible(true);
            jTextFieldNombre.setText("");
            jTextFieldDireccion.setText("");
            jTextFieldTelefono.setText("");
            jTextFieldFecha.setText("");
            jTextFieldEmail.setText("");
           
       }
    }//GEN-LAST:event_jButtonBuscarMouseClicked

    private void jTextFieldBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBuscarMouseClicked
        jTextFieldBuscar.setText("");
    }//GEN-LAST:event_jTextFieldBuscarMouseClicked

    private Usuario user;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jButtonBuscar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelAsterisco10;
    private javax.swing.JLabel jLabelAsterisco11;
    private javax.swing.JLabel jLabelAsterisco13;
    private javax.swing.JLabel jLabelAsterisco14;
    private javax.swing.JLabel jLabelAsterisco15;
    private javax.swing.JLabel jLabelAsterisco16;
    private javax.swing.JLabel jLabelCC;
    private javax.swing.JLabel jLabelCodigo1;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelImageExit1;
    private javax.swing.JLabel jLabelMiniUser1;
    private javax.swing.JLabel jLabelMiniUser2;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono1;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelUserName1;
    private javax.swing.JLabel jLabelWindowTitle;
    private javax.swing.JPanel jPaneMenuLateral;
    private javax.swing.JPanel jPaneMenuLateral1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelMenu1;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPanel jPanelTitulo3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
